

namespace Generator
{

    public class AllDataWorking
    {
        public string Division { get; set; }
        public string Product { get; set; }
        public int? Application92KfiNo46 { get; set; }
        public string PaReferenceNumber { get; set; }
        public string NewPaReference { get; set; }
        public System.DateTime? DateSubmitted { get; set; }
        public string App1Title { get; set; }
        public string App1Surname { get; set; }
        public System.DateTime? App1D46O46B46 { get; set; }
        public string App1Gender { get; set; }
        public string App2Title { get; set; }
        public string App2Surname { get; set; }
        public System.DateTime? App2D46O46B46 { get; set; }
        public string App2Gender { get; set; }
        public decimal? LoanAmount { get; set; }
        public string BrokerName { get; set; }
        public string BrokerFirm1 { get; set; }
        public string Street40Broker41 { get; set; }
        public string District { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public string FcaNumber1 { get; set; }
        public string LoanProduct { get; set; }
        public string PegPercentage { get; set; }
        public int OnAppRegister { get; set; }
        public int RealCount { get; set; }
        public string Id { get; set; }
        public int LatestVersion { get; set; }
        public int? ProperCount { get; set; }
        public System.DateTime? ApplicationDate { get; set; }
        public System.DateTime? ValuationDate { get; set; }
        public System.DateTime? OfferDate { get; set; }
        public System.DateTime? ActualCompletionDate1 { get; set; }
        public System.DateTime? DeclinedDate { get; set; }
        public System.DateTime? WithdrawnDate1 { get; set; }
        public string Status { get; set; }
        public int Blank { get; set; }
        public int Withdrawn { get; set; }
        public int Declined { get; set; }
        public int Complete { get; set; }
        public int CompletionDateSet { get; set; }
        public int Offer { get; set; }
        public int ApplicationReceived { get; set; }
        public int Kfi6030Days { get; set; }
        public int Kfi6230Days { get; set; }
        public int DateChangeToday { get; set; }
        public int LastAction622MonthsAgo { get; set; }
        public double? KfiWeek1 { get; set; }
        public double? AppWeek1 { get; set; }
        public double? OfferWeek1 { get; set; }
        public double? CompletionWeek { get; set; }
        public System.DateTime? KfiMonth1 { get; set; }
        public System.DateTime? AppMonth1 { get; set; }
        public System.DateTime? OfferMonth1 { get; set; }
        public System.DateTime? CompletionMonth { get; set; }
        public int? KfiDays { get; set; }
        public int? AppDays { get; set; }
        public int? OfferDays { get; set; }
        public string Underwriter { get; set; }
        public int? StillToDealWith { get; set; }
        public int? DaysToDealWithApp { get; set; }
        public int? Kfiid { get; set; }
        public string IssueBy { get; set; }
        public string SubBrokerRef { get; set; }
        public string Brokerref { get; set; }
        public string PlanRef { get; set; }
        public string PlanName { get; set; }
        public string PlanFunderRef { get; set; }
        public string Funder { get; set; }
        public string BrokerFirm { get; set; }
        public string BrokerAgentForename { get; set; }
        public string BrokerAgentSurname { get; set; }
        public string BrokerCareOf { get; set; }
        public string BrokerStreet { get; set; }
        public string BrokerDistrict { get; set; }
        public string BrokerTown { get; set; }
        public string BrokerCounty { get; set; }
        public string BrokerPostCode { get; set; }
        public string BrokerFcaNumber { get; set; }
        public string LoanPurpose { get; set; }
        public System.DateTime? KfiDate { get; set; }
        public System.DateTime? KfiExpiryDate { get; set; }
        public string KfiType { get; set; }
        public string FullCustomerName { get; set; }
        public string C1Title { get; set; }
        public string C1Forename { get; set; }
        public string C1Surname { get; set; }
        public System.DateTime? C1Dob { get; set; }
        public string C1Gender { get; set; }
        public string C2Title { get; set; }
        public string C2Forename { get; set; }
        public string C2Surname { get; set; }
        public System.DateTime? C2Dob { get; set; }
        public string PropertyType { get; set; }
        public string PropertyConstruction { get; set; }
        public string PropertyMainResidence { get; set; }
        public string PropertyPrivateDwelling { get; set; }
        public string UkResident { get; set; }
        public string CcjNumber { get; set; }
        public string CcjValue { get; set; }
        public string IvaDetails { get; set; }
        public string BankruptcyDetails { get; set; }
        public decimal? NetLoanAmount { get; set; }
        public decimal? FeesToBeAdded { get; set; }
        public decimal? FeesToBePaid { get; set; }
        public decimal? ValuationFee { get; set; }
        public decimal? ApplicationFee { get; set; }
        public bool? ApplicationFeeAddedFlag { get; set; }
        public decimal? AcceptanceFee { get; set; }
        public bool? AcceptanceFeeAddedFlag { get; set; }
        public decimal? CompletionFee { get; set; }
        public bool? CompletionFeeAddedFlag { get; set; }
        public decimal? LasiFee { get; set; }
        public bool? LasiFeeAddedFlag { get; set; }
        public decimal? FundTransferFee { get; set; }
        public bool? FundTransferFeeAddedFlag { get; set; }
        public decimal? OtherCompletionFee { get; set; }
        public decimal? LoanRedemptionFee { get; set; }
        public decimal? SolicitorFee { get; set; }
        public bool? SolicitorFeeAddedFlag { get; set; }
        public decimal? AdvisorFee { get; set; }
        public bool? AdvisorFeeAddedFlag { get; set; }
        public decimal? PropertyValue { get; set; }
        public string AprRate { get; set; }
        public decimal? GrossLoanAmount { get; set; }
        public decimal? TotalAllFees { get; set; }
        public System.DateTime? AcceptanceDate { get; set; }
        public System.DateTime? AppRecvDate { get; set; }
        public string InternalRefNumber1 { get; set; }
        public string FriendlyName { get; set; }
        public string BdmName { get; set; }
        public long? RowNumClientBroker { get; set; }
        public long? RowNumClient { get; set; }
        public string AppType { get; set; }
        public string BusregDivision { get; set; }
        public string KfiNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string AccountNo { get; set; }
        public string CustomerRef { get; set; }
        public string AcctRef { get; set; }
        public System.DateTime? DateKfiCreated { get; set; }
        public double? KfiWeek { get; set; }
        public System.DateTime? KfiMonth { get; set; }
        public System.DateTime? DateAppReceived { get; set; }
        public double? AppWeek { get; set; }
        public System.DateTime? AppMonth { get; set; }
        public System.DateTime? OfferIssuedDate { get; set; }
        public double? OfferWeek { get; set; }
        public System.DateTime? OfferMonth { get; set; }
        public System.DateTime? AnticipatedCompletionDate { get; set; }
        public System.DateTime? ActualCompletionDate { get; set; }
        public double? CompWeek { get; set; }
        public System.DateTime? CompMonth { get; set; }
        public string SingleOrJointApplication { get; set; }
        public string Life1Title { get; set; }
        public string Life1Forename { get; set; }
        public string Life1Surname { get; set; }
        public System.DateTime? Life1Dob { get; set; }
        public string Life1Sex { get; set; }
        public string MaritalStatusLife1 { get; set; }
        public string Life2Title { get; set; }
        public string Life2Forename { get; set; }
        public string Life2Surname { get; set; }
        public System.DateTime? Life2Dob { get; set; }
        public string Life2Sex { get; set; }
        public string MaritalStatusLife2 { get; set; }
        public decimal? EstimatedPropertyValue { get; set; }
        public decimal? SurveyorsPropertyValue { get; set; }
        public System.DateTime? DateOfSurveyorsPropertyValue { get; set; }
        public string ValuationMethod { get; set; }
        public decimal? InitialLoanAmountRequested { get; set; }
        public string ArrangementFeeAddedToLoan { get; set; }
        public decimal? ArrangementFee { get; set; }
        public decimal? InitialLoanRequestedIncFeesAdded { get; set; }
        public decimal? CurrentRetentionBalance { get; set; }
        public decimal? ActualLoanReleasedOnCompletion { get; set; }
        public decimal? RetentionBalanceReleased { get; set; }
        public decimal? TotalLoanReleasedToCustomer { get; set; }
        public decimal? MaximumDrawdownLimit { get; set; }
        public decimal? ChosenDrawdownLimit { get; set; }
        public decimal? DrawdownFacilityAvailableAtCompletion { get; set; }
        public decimal? TotalFacilityAllocatedToCustomerIncludingRetentionsExcludingFees { get; set; }
        public int? DrawdownsMade { get; set; }
        public decimal? DrawdownAmountTaken { get; set; }
        public decimal? RemainingDrawdownFacility { get; set; }
        public string ClientRegion { get; set; }
        public string ClientStreet { get; set; }
        public string ClientDistrict { get; set; }
        public string ClientTown { get; set; }
        public string ClientCounty { get; set; }
        public string ClientPostcode { get; set; }
        public double? EstLtv { get; set; }
        public double? ActualLtv { get; set; }
        public string FcaNumber { get; set; }
        public double? InterestRate { get; set; }
        public string FreeVal { get; set; }
        public string RefundOfValuationFee { get; set; }
        public decimal? Commission { get; set; }
        public decimal? AdviceFee { get; set; }
        public decimal? ContributionToAdviceFee { get; set; }
        public decimal? ContributionToLegalFee { get; set; }
        public string BusregStatus { get; set; }
        public System.DateTime? StatusChangeDate { get; set; }
        public string Rejectionreasona { get; set; }
        public string Rejectionreasonb { get; set; }
        public string BrokerClub { get; set; }
        public string DaysOld { get; set; }
        public string UploadedBy { get; set; }
        public string BusregUnderwriter { get; set; }
        public string InternalRefNumber { get; set; }
        public System.DateTime? WithdrawnDate { get; set; }
        public System.DateTime? RejectedDate { get; set; }
        public decimal? InterestAppliedToDate { get; set; }
        public decimal? InterestDueToBeApplied { get; set; }
        public decimal? RedemptionsToDate { get; set; }
        public string AccountStatus { get; set; }
        public System.DateTime? AccountClosureDate { get; set; }
        public string BrokerAgentRef { get; set; }
        public string OfficialRegion { get; set; }
        public int? Life1Age { get; set; }
        public int? Life2Age { get; set; }
        public int? YoungestAge { get; set; }
        public int? ProperCountMonth { get; set; }
        public int? ProperCountWeek { get; set; }
        public int? ProperCountMonthApp { get; set; }
        public int? ProperCountWeekApp { get; set; }
        public bool IsFieldBased { get; set; }
        public int PackagerMortgageId { get; set; }
    }

}
