

namespace Generator
{

    public class Crik
    {
        public int Crik001 { get; set; }
        public string Crik105 { get; set; }
        public string Crik120 { get; set; }
        public string Crik125 { get; set; }
        public string Crik130 { get; set; }
        public string Crik235 { get; set; }
        public string Crik250 { get; set; }
        public string Crik265 { get; set; }
        public string Crik270 { get; set; }
        public string Crik275 { get; set; }
        public string Crik300 { get; set; }
        public string Crik305 { get; set; }
        public string Crik310 { get; set; }
        public string Crik315 { get; set; }
        public string Crik320 { get; set; }
        public string Crik400 { get; set; }
        public string Crik405 { get; set; }
        public string Crik435 { get; set; }
        public string Crik460 { get; set; }
        public string Crik605 { get; set; }
        public string Crik620 { get; set; }
        public string Crik625 { get; set; }
        public string Crik630 { get; set; }
        public string Crik735 { get; set; }
        public string Crik750 { get; set; }
        public string Crik765 { get; set; }
        public string Crik770 { get; set; }
        public string Crik775 { get; set; }
        public string Crik800 { get; set; }
        public string Crik805 { get; set; }
        public string Crik810 { get; set; }
        public string Crik815 { get; set; }
        public string Crik820 { get; set; }
        public string Crik900 { get; set; }
        public string Crik905 { get; set; }
        public string Crik935 { get; set; }
        public string Crik960 { get; set; }
        public string Crik121 { get; set; }
        public string Crik131 { get; set; }
        public string Crik240 { get; set; }
        public string Crik277 { get; set; }
        public string Crik280 { get; set; }
        public string Crik281 { get; set; }
        public string Crik282 { get; set; }
        public string Crik410 { get; set; }
        public string Crik470 { get; set; }
        public string Crik471 { get; set; }
        public string Crik472 { get; set; }
        public string Crik473 { get; set; }
        public string Crik474 { get; set; }
        public string Crik475 { get; set; }
        public string Crik476 { get; set; }
        public string Crik477 { get; set; }
        public string Crik621 { get; set; }
        public string Crik740 { get; set; }
        public string Crik631 { get; set; }
        public string Crik777 { get; set; }
        public string Crik780 { get; set; }
        public string Crik781 { get; set; }
        public string Crik782 { get; set; }
        public string Crik910 { get; set; }
        public string Crik970 { get; set; }
        public string Crik971 { get; set; }
        public string Crik972 { get; set; }
        public string Crik973 { get; set; }
        public string Crik974 { get; set; }
        public string Crik975 { get; set; }
        public string Crik976 { get; set; }
        public string Crik977 { get; set; }
        public int Crik020 { get; set; }
        public System.DateTime Crik030 { get; set; }
        public string Crik122 { get; set; }
        public string Crik622 { get; set; }
        public string Crik478 { get; set; }
        public string Crik978 { get; set; }
        public string Crik483 { get; set; }
        public string Crik983 { get; set; }
        public string Crik485 { get; set; }
        public string Crik486 { get; set; }
        public string Crik487 { get; set; }
        public string Crik488 { get; set; }
        public string Crik489 { get; set; }
        public string Crik985 { get; set; }
        public string Crik986 { get; set; }
        public string Crik987 { get; set; }
        public string Crik988 { get; set; }
        public string Crik989 { get; set; }
        public string Crik312 { get; set; }
        public string Crik812 { get; set; }
        public string Crik340 { get; set; }
        public string Crik840 { get; set; }
        public string Crik490 { get; set; }
        public string Crik990 { get; set; }
        public string Crik491 { get; set; }
        public string Crik991 { get; set; }
        public string Crik492 { get; set; }
        public string Crik992 { get; set; }
        public string Crik290 { get; set; }
        public string Crik790 { get; set; }
    }

}
