

namespace Generator
{

    public class Fsa
    {
        public int Fsas000 { get; set; }
        public System.DateTime Fsas001 { get; set; }
        public string Fsas002 { get; set; }
        public int Fsas010 { get; set; }
        public int Fsas011 { get; set; }
        public int Fsas012 { get; set; }
        public int Fsas013 { get; set; }
        public int Fsas014 { get; set; }
        public int Fsas015 { get; set; }
        public decimal Fsas020 { get; set; }
        public decimal Fsas021 { get; set; }
        public decimal Fsas022 { get; set; }
        public decimal Fsas023 { get; set; }
        public decimal Fsas024 { get; set; }
        public decimal Fsas025 { get; set; }
        public decimal Fsas030 { get; set; }
        public decimal Fsas031 { get; set; }
        public decimal Fsas032 { get; set; }
        public decimal Fsas033 { get; set; }
        public decimal Fsas034 { get; set; }
        public decimal Fsas035 { get; set; }
        public int Fsas040 { get; set; }
        public int Fsas041 { get; set; }
        public int Fsas042 { get; set; }
        public int Fsas043 { get; set; }
        public int Fsas044 { get; set; }
        public int Fsas045 { get; set; }
        public decimal Fsas050 { get; set; }
        public decimal Fsas051 { get; set; }
        public decimal Fsas052 { get; set; }
        public decimal Fsas053 { get; set; }
        public decimal Fsas054 { get; set; }
        public decimal Fsas055 { get; set; }
        public decimal Fsas060 { get; set; }
        public decimal Fsas061 { get; set; }
        public decimal Fsas062 { get; set; }
        public decimal Fsas063 { get; set; }
        public decimal Fsas064 { get; set; }
        public decimal Fsas065 { get; set; }
        public int Fsas100 { get; set; }
        public int Fsas101 { get; set; }
        public int Fsas102 { get; set; }
        public int Fsas103 { get; set; }
        public int Fsas104 { get; set; }
        public int Fsas105 { get; set; }
        public decimal Fsas110 { get; set; }
        public decimal Fsas111 { get; set; }
        public decimal Fsas112 { get; set; }
        public decimal Fsas113 { get; set; }
        public decimal Fsas114 { get; set; }
        public decimal Fsas115 { get; set; }
        public decimal Fsas120 { get; set; }
        public decimal Fsas121 { get; set; }
        public decimal Fsas122 { get; set; }
        public decimal Fsas123 { get; set; }
        public decimal Fsas124 { get; set; }
        public decimal Fsas125 { get; set; }
        public int Fsas130 { get; set; }
        public int Fsas131 { get; set; }
        public int Fsas132 { get; set; }
        public int Fsas133 { get; set; }
        public int Fsas134 { get; set; }
        public int Fsas135 { get; set; }
        public decimal Fsas140 { get; set; }
        public decimal Fsas141 { get; set; }
        public decimal Fsas142 { get; set; }
        public decimal Fsas143 { get; set; }
        public decimal Fsas144 { get; set; }
        public decimal Fsas145 { get; set; }
        public decimal Fsas150 { get; set; }
        public decimal Fsas151 { get; set; }
        public decimal Fsas152 { get; set; }
        public decimal Fsas153 { get; set; }
        public decimal Fsas154 { get; set; }
        public decimal Fsas155 { get; set; }
        public int Fsas160 { get; set; }
        public int Fsas161 { get; set; }
        public int Fsas162 { get; set; }
        public int Fsas163 { get; set; }
        public int Fsas164 { get; set; }
        public int Fsas165 { get; set; }
        public decimal Fsas170 { get; set; }
        public decimal Fsas171 { get; set; }
        public decimal Fsas172 { get; set; }
        public decimal Fsas173 { get; set; }
        public decimal Fsas174 { get; set; }
        public decimal Fsas175 { get; set; }
        public decimal Fsas180 { get; set; }
        public decimal Fsas181 { get; set; }
        public decimal Fsas182 { get; set; }
        public decimal Fsas183 { get; set; }
        public decimal Fsas184 { get; set; }
        public decimal Fsas185 { get; set; }
        public int Fsas220 { get; set; }
        public int Fsas221 { get; set; }
        public int Fsas222 { get; set; }
        public int Fsas223 { get; set; }
        public int Fsas224 { get; set; }
        public int Fsas225 { get; set; }
        public decimal Fsas230 { get; set; }
        public decimal Fsas231 { get; set; }
        public decimal Fsas232 { get; set; }
        public decimal Fsas233 { get; set; }
        public decimal Fsas234 { get; set; }
        public decimal Fsas235 { get; set; }
        public decimal Fsas240 { get; set; }
        public decimal Fsas241 { get; set; }
        public decimal Fsas242 { get; set; }
        public decimal Fsas243 { get; set; }
        public decimal Fsas244 { get; set; }
        public decimal Fsas245 { get; set; }
        public decimal Fsas250 { get; set; }
        public decimal Fsas251 { get; set; }
        public decimal Fsas252 { get; set; }
        public decimal Fsas253 { get; set; }
        public decimal Fsas254 { get; set; }
        public decimal Fsas255 { get; set; }
        public decimal Fsas256 { get; set; }
        public decimal Fsas260 { get; set; }
        public decimal Fsas261 { get; set; }
        public decimal Fsas262 { get; set; }
        public decimal Fsas263 { get; set; }
        public decimal Fsas264 { get; set; }
        public decimal Fsas265 { get; set; }
        public decimal Fsas266 { get; set; }
        public decimal Fsas270 { get; set; }
        public decimal Fsas271 { get; set; }
        public decimal Fsas272 { get; set; }
        public decimal Fsas273 { get; set; }
        public decimal Fsas274 { get; set; }
        public decimal Fsas275 { get; set; }
        public decimal Fsas276 { get; set; }
        public decimal Fsas280 { get; set; }
        public decimal Fsas281 { get; set; }
        public decimal Fsas282 { get; set; }
        public decimal Fsas283 { get; set; }
        public decimal Fsas284 { get; set; }
        public decimal Fsas285 { get; set; }
        public decimal Fsas286 { get; set; }
        public int Fsas290 { get; set; }
        public decimal Fsas291 { get; set; }
        public int Fsas292 { get; set; }
        public decimal Fsas293 { get; set; }
        public decimal Fsas294 { get; set; }
        public int Fsas295 { get; set; }
        public int Fsas296 { get; set; }
        public int Fsas300 { get; set; }
        public decimal Fsas301 { get; set; }
        public int Fsas302 { get; set; }
        public decimal Fsas303 { get; set; }
        public decimal Fsas304 { get; set; }
        public int Fsas305 { get; set; }
        public int Fsas306 { get; set; }
        public int Fsas320 { get; set; }
        public decimal Fsas321 { get; set; }
        public int Fsas322 { get; set; }
        public decimal Fsas323 { get; set; }
        public decimal Fsas324 { get; set; }
        public int Fsas325 { get; set; }
        public int Fsas326 { get; set; }
        public string Fsas340 { get; set; }
        public int Fsas341 { get; set; }
        public int Fsas342 { get; set; }
        public int Fsas343 { get; set; }
        public decimal Fsas345 { get; set; }
        public decimal Fsas346 { get; set; }
        public decimal Fsas347 { get; set; }
        public int Fsas351 { get; set; }
        public int Fsas352 { get; set; }
        public int Fsas353 { get; set; }
        public decimal Fsas355 { get; set; }
        public decimal Fsas356 { get; set; }
        public decimal Fsas357 { get; set; }
        public int Fsas371 { get; set; }
        public int Fsas372 { get; set; }
        public int Fsas373 { get; set; }
        public decimal Fsas375 { get; set; }
        public decimal Fsas376 { get; set; }
        public decimal Fsas377 { get; set; }
        public int Fsas381 { get; set; }
        public int Fsas382 { get; set; }
        public int Fsas383 { get; set; }
        public decimal Fsas385 { get; set; }
        public decimal Fsas386 { get; set; }
        public decimal Fsas387 { get; set; }
        public int Fsas4001 { get; set; }
        public int Fsas4002 { get; set; }
        public int Fsas4003 { get; set; }
        public int Fsas4004 { get; set; }
        public int Fsas4005 { get; set; }
        public string Fsas4011 { get; set; }
        public string Fsas4012 { get; set; }
        public string Fsas4013 { get; set; }
        public string Fsas4014 { get; set; }
        public string Fsas4015 { get; set; }
        public decimal Fsas4021 { get; set; }
        public decimal Fsas4022 { get; set; }
        public decimal Fsas4023 { get; set; }
        public decimal Fsas4024 { get; set; }
        public decimal Fsas4025 { get; set; }
        public decimal Fsas4031 { get; set; }
        public decimal Fsas4032 { get; set; }
        public decimal Fsas4033 { get; set; }
        public decimal Fsas4034 { get; set; }
        public decimal Fsas4035 { get; set; }
        public decimal Fsas4041 { get; set; }
        public decimal Fsas4042 { get; set; }
        public decimal Fsas4043 { get; set; }
        public decimal Fsas4044 { get; set; }
        public decimal Fsas4045 { get; set; }
        public string Fsas4051 { get; set; }
        public string Fsas4052 { get; set; }
        public string Fsas4053 { get; set; }
        public string Fsas4054 { get; set; }
        public string Fsas4055 { get; set; }
        public int Fsas4101 { get; set; }
        public int Fsas4102 { get; set; }
        public int Fsas4103 { get; set; }
        public int Fsas4104 { get; set; }
        public int Fsas4105 { get; set; }
        public string Fsas4111 { get; set; }
        public string Fsas4112 { get; set; }
        public string Fsas4113 { get; set; }
        public string Fsas4114 { get; set; }
        public string Fsas4115 { get; set; }
        public decimal Fsas4121 { get; set; }
        public decimal Fsas4122 { get; set; }
        public decimal Fsas4123 { get; set; }
        public decimal Fsas4124 { get; set; }
        public decimal Fsas4125 { get; set; }
        public decimal Fsas4131 { get; set; }
        public decimal Fsas4132 { get; set; }
        public decimal Fsas4133 { get; set; }
        public decimal Fsas4134 { get; set; }
        public decimal Fsas4135 { get; set; }
        public decimal Fsas4141 { get; set; }
        public decimal Fsas4142 { get; set; }
        public decimal Fsas4143 { get; set; }
        public decimal Fsas4144 { get; set; }
        public decimal Fsas4145 { get; set; }
        public string Fsas4151 { get; set; }
        public string Fsas4152 { get; set; }
        public string Fsas4153 { get; set; }
        public string Fsas4154 { get; set; }
        public string Fsas4155 { get; set; }
        public int Fsas4201 { get; set; }
        public int Fsas4202 { get; set; }
        public int Fsas4203 { get; set; }
        public int Fsas4204 { get; set; }
        public int Fsas4205 { get; set; }
        public string Fsas4211 { get; set; }
        public string Fsas4212 { get; set; }
        public string Fsas4213 { get; set; }
        public string Fsas4214 { get; set; }
        public string Fsas4215 { get; set; }
        public decimal Fsas4221 { get; set; }
        public decimal Fsas4222 { get; set; }
        public decimal Fsas4223 { get; set; }
        public decimal Fsas4224 { get; set; }
        public decimal Fsas4225 { get; set; }
        public decimal Fsas4231 { get; set; }
        public decimal Fsas4232 { get; set; }
        public decimal Fsas4233 { get; set; }
        public decimal Fsas4234 { get; set; }
        public decimal Fsas4235 { get; set; }
        public decimal Fsas4241 { get; set; }
        public decimal Fsas4242 { get; set; }
        public decimal Fsas4243 { get; set; }
        public decimal Fsas4244 { get; set; }
        public decimal Fsas4245 { get; set; }
        public string Fsas4251 { get; set; }
        public string Fsas4252 { get; set; }
        public string Fsas4253 { get; set; }
        public string Fsas4254 { get; set; }
        public string Fsas4255 { get; set; }
        public int Fsas430 { get; set; }
        public int Fsas431 { get; set; }
        public int Fsas432 { get; set; }
        public int Fsas433 { get; set; }
        public int Fsas434 { get; set; }
        public int Fsas435 { get; set; }
        public decimal Fsas440 { get; set; }
        public decimal Fsas441 { get; set; }
        public decimal Fsas442 { get; set; }
        public decimal Fsas443 { get; set; }
        public decimal Fsas444 { get; set; }
        public decimal Fsas445 { get; set; }
        public decimal Fsas450 { get; set; }
        public decimal Fsas451 { get; set; }
        public decimal Fsas452 { get; set; }
        public decimal Fsas453 { get; set; }
        public decimal Fsas454 { get; set; }
        public decimal Fsas455 { get; set; }
        public int Fsas460 { get; set; }
        public int Fsas461 { get; set; }
        public int Fsas462 { get; set; }
        public int Fsas463 { get; set; }
        public int Fsas464 { get; set; }
        public int Fsas465 { get; set; }
        public decimal Fsas470 { get; set; }
        public decimal Fsas471 { get; set; }
        public decimal Fsas472 { get; set; }
        public decimal Fsas473 { get; set; }
        public decimal Fsas474 { get; set; }
        public decimal Fsas475 { get; set; }
        public decimal Fsas480 { get; set; }
        public decimal Fsas481 { get; set; }
        public decimal Fsas482 { get; set; }
        public decimal Fsas483 { get; set; }
        public decimal Fsas484 { get; set; }
        public decimal Fsas485 { get; set; }
        public int Fsas520 { get; set; }
        public int Fsas521 { get; set; }
        public int Fsas522 { get; set; }
        public int Fsas523 { get; set; }
        public int Fsas524 { get; set; }
        public int Fsas525 { get; set; }
        public decimal Fsas530 { get; set; }
        public decimal Fsas531 { get; set; }
        public decimal Fsas532 { get; set; }
        public decimal Fsas533 { get; set; }
        public decimal Fsas534 { get; set; }
        public decimal Fsas535 { get; set; }
        public decimal Fsas540 { get; set; }
        public decimal Fsas541 { get; set; }
        public decimal Fsas542 { get; set; }
        public decimal Fsas543 { get; set; }
        public decimal Fsas544 { get; set; }
        public decimal Fsas545 { get; set; }
        public int Fsas550 { get; set; }
        public int Fsas551 { get; set; }
        public int Fsas552 { get; set; }
        public int Fsas553 { get; set; }
        public int Fsas554 { get; set; }
        public int Fsas555 { get; set; }
        public decimal Fsas560 { get; set; }
        public decimal Fsas561 { get; set; }
        public decimal Fsas562 { get; set; }
        public decimal Fsas563 { get; set; }
        public decimal Fsas564 { get; set; }
        public decimal Fsas565 { get; set; }
        public decimal Fsas570 { get; set; }
        public decimal Fsas571 { get; set; }
        public decimal Fsas572 { get; set; }
        public decimal Fsas573 { get; set; }
        public decimal Fsas574 { get; set; }
        public decimal Fsas575 { get; set; }
        public decimal Fsas610 { get; set; }
        public decimal Fsas611 { get; set; }
        public decimal Fsas612 { get; set; }
        public decimal Fsas613 { get; set; }
        public decimal Fsas614 { get; set; }
        public decimal Fsas615 { get; set; }
        public decimal Fsas616 { get; set; }
        public decimal Fsas620 { get; set; }
        public decimal Fsas621 { get; set; }
        public decimal Fsas622 { get; set; }
        public decimal Fsas623 { get; set; }
        public decimal Fsas624 { get; set; }
        public decimal Fsas625 { get; set; }
        public decimal Fsas626 { get; set; }
        public decimal Fsas630 { get; set; }
        public decimal Fsas631 { get; set; }
        public decimal Fsas632 { get; set; }
        public decimal Fsas633 { get; set; }
        public decimal Fsas634 { get; set; }
        public decimal Fsas635 { get; set; }
        public decimal Fsas636 { get; set; }
        public int Fsas640 { get; set; }
        public decimal Fsas641 { get; set; }
        public int Fsas642 { get; set; }
        public decimal Fsas643 { get; set; }
        public decimal Fsas644 { get; set; }
        public int Fsas645 { get; set; }
        public int Fsas646 { get; set; }
        public int Fsas650 { get; set; }
        public decimal Fsas651 { get; set; }
        public int Fsas652 { get; set; }
        public decimal Fsas653 { get; set; }
        public decimal Fsas654 { get; set; }
        public int Fsas655 { get; set; }
        public int Fsas656 { get; set; }
        public decimal Fsas671 { get; set; }
        public decimal Fsas672 { get; set; }
        public decimal Fsas675 { get; set; }
        public decimal Fsas677 { get; set; }
        public decimal Fsas679 { get; set; }
        public decimal Fsas680 { get; set; }
        public decimal Fsas682 { get; set; }
        public string Fsas007 { get; set; }
    }

}
