

namespace Generator
{

    public class Fsar
    {
        public int Fsar000 { get; set; }
        public System.DateTime Fsar001 { get; set; }
        public string Fsar002 { get; set; }
        public decimal Fsar010 { get; set; }
        public decimal Fsar011 { get; set; }
        public decimal Fsar012 { get; set; }
        public decimal Fsar013 { get; set; }
        public decimal Fsar015 { get; set; }
        public decimal Fsar017 { get; set; }
        public decimal Fsar018 { get; set; }
        public decimal Fsar019 { get; set; }
        public decimal Fsar020 { get; set; }
        public decimal Fsar021 { get; set; }
        public decimal Fsar022 { get; set; }
        public decimal Fsar024 { get; set; }
        public decimal Fsar030 { get; set; }
        public decimal Fsar031 { get; set; }
        public decimal Fsar032 { get; set; }
        public decimal Fsar033 { get; set; }
        public decimal Fsar035 { get; set; }
        public decimal Fsar037 { get; set; }
        public decimal Fsar038 { get; set; }
        public decimal Fsar039 { get; set; }
        public decimal Fsar040 { get; set; }
        public decimal Fsar041 { get; set; }
        public decimal Fsar042 { get; set; }
        public decimal Fsar044 { get; set; }
        public decimal Fsar050 { get; set; }
        public decimal Fsar051 { get; set; }
        public decimal Fsar052 { get; set; }
        public decimal Fsar053 { get; set; }
        public decimal Fsar055 { get; set; }
        public decimal Fsar057 { get; set; }
        public decimal Fsar058 { get; set; }
        public decimal Fsar059 { get; set; }
        public decimal Fsar060 { get; set; }
        public decimal Fsar061 { get; set; }
        public decimal Fsar062 { get; set; }
        public decimal Fsar064 { get; set; }
        public decimal Fsar090 { get; set; }
        public decimal Fsar091 { get; set; }
        public decimal Fsar092 { get; set; }
        public decimal Fsar093 { get; set; }
        public decimal Fsar094 { get; set; }
        public decimal Fsar095 { get; set; }
        public decimal Fsar096 { get; set; }
        public decimal Fsar097 { get; set; }
        public decimal Fsar098 { get; set; }
        public decimal Fsar099 { get; set; }
        public decimal Fsar100 { get; set; }
        public decimal Fsar101 { get; set; }
        public decimal Fsar102 { get; set; }
        public decimal Fsar103 { get; set; }
        public decimal Fsar104 { get; set; }
        public decimal Fsar105 { get; set; }
        public decimal Fsar106 { get; set; }
        public decimal Fsar107 { get; set; }
        public decimal Fsar108 { get; set; }
        public decimal Fsar109 { get; set; }
        public decimal Fsar110 { get; set; }
        public decimal Fsar111 { get; set; }
        public decimal Fsar112 { get; set; }
        public decimal Fsar113 { get; set; }
        public decimal Fsar114 { get; set; }
        public decimal Fsar115 { get; set; }
        public decimal Fsar116 { get; set; }
        public decimal Fsar117 { get; set; }
        public decimal Fsar118 { get; set; }
        public decimal Fsar119 { get; set; }
        public decimal Fsar120 { get; set; }
        public decimal Fsar121 { get; set; }
        public decimal Fsar122 { get; set; }
        public decimal Fsar123 { get; set; }
        public decimal Fsar124 { get; set; }
        public decimal Fsar125 { get; set; }
        public decimal Fsar126 { get; set; }
        public decimal Fsar127 { get; set; }
        public decimal Fsar128 { get; set; }
        public decimal Fsar129 { get; set; }
        public decimal Fsar130 { get; set; }
        public decimal Fsar131 { get; set; }
        public decimal Fsar132 { get; set; }
        public decimal Fsar133 { get; set; }
        public decimal Fsar134 { get; set; }
        public decimal Fsar135 { get; set; }
        public decimal Fsar136 { get; set; }
        public decimal Fsar137 { get; set; }
        public decimal Fsar138 { get; set; }
        public decimal Fsar139 { get; set; }
        public decimal Fsar140 { get; set; }
        public decimal Fsar141 { get; set; }
        public decimal Fsar142 { get; set; }
        public decimal Fsar143 { get; set; }
        public decimal Fsar144 { get; set; }
        public decimal Fsar145 { get; set; }
        public decimal Fsar146 { get; set; }
        public decimal Fsar147 { get; set; }
        public decimal Fsar148 { get; set; }
        public decimal Fsar149 { get; set; }
        public decimal Fsar157 { get; set; }
        public decimal Fsar158 { get; set; }
        public decimal Fsar159 { get; set; }
        public decimal Fsar167 { get; set; }
        public decimal Fsar168 { get; set; }
        public decimal Fsar169 { get; set; }
        public decimal Fsar170 { get; set; }
        public decimal Fsar171 { get; set; }
        public decimal Fsar172 { get; set; }
        public decimal Fsar174 { get; set; }
        public decimal Fsar175 { get; set; }
        public decimal Fsar176 { get; set; }
        public decimal Fsar178 { get; set; }
        public decimal Fsar180 { get; set; }
        public decimal Fsar181 { get; set; }
        public decimal Fsar182 { get; set; }
        public decimal Fsar184 { get; set; }
        public decimal Fsar185 { get; set; }
        public decimal Fsar186 { get; set; }
        public decimal Fsar188 { get; set; }
        public decimal Fsar190 { get; set; }
        public decimal Fsar191 { get; set; }
        public decimal Fsar192 { get; set; }
        public decimal Fsar194 { get; set; }
        public decimal Fsar195 { get; set; }
        public decimal Fsar196 { get; set; }
        public decimal Fsar198 { get; set; }
        public decimal Fsar200 { get; set; }
        public decimal Fsar201 { get; set; }
        public decimal Fsar202 { get; set; }
        public decimal Fsar204 { get; set; }
        public decimal Fsar205 { get; set; }
        public decimal Fsar206 { get; set; }
        public decimal Fsar208 { get; set; }
        public decimal Fsar210 { get; set; }
        public decimal Fsar211 { get; set; }
        public decimal Fsar212 { get; set; }
        public decimal Fsar214 { get; set; }
        public decimal Fsar215 { get; set; }
        public decimal Fsar216 { get; set; }
        public decimal Fsar218 { get; set; }
        public decimal Fsar220 { get; set; }
        public decimal Fsar221 { get; set; }
        public decimal Fsar222 { get; set; }
        public decimal Fsar224 { get; set; }
        public decimal Fsar225 { get; set; }
        public decimal Fsar226 { get; set; }
        public decimal Fsar228 { get; set; }
        public decimal Fsar300 { get; set; }
        public decimal Fsar301 { get; set; }
        public decimal Fsar302 { get; set; }
        public decimal Fsar303 { get; set; }
        public decimal Fsar304 { get; set; }
        public decimal Fsar305 { get; set; }
        public decimal Fsar307 { get; set; }
        public decimal Fsar310 { get; set; }
        public decimal Fsar311 { get; set; }
        public decimal Fsar312 { get; set; }
        public decimal Fsar313 { get; set; }
        public decimal Fsar314 { get; set; }
        public decimal Fsar315 { get; set; }
        public decimal Fsar317 { get; set; }
        public decimal Fsar320 { get; set; }
        public decimal Fsar321 { get; set; }
        public decimal Fsar322 { get; set; }
        public decimal Fsar323 { get; set; }
        public decimal Fsar324 { get; set; }
        public decimal Fsar325 { get; set; }
        public decimal Fsar327 { get; set; }
        public decimal Fsar330 { get; set; }
        public decimal Fsar331 { get; set; }
        public decimal Fsar332 { get; set; }
        public decimal Fsar333 { get; set; }
        public decimal Fsar334 { get; set; }
        public decimal Fsar335 { get; set; }
        public decimal Fsar337 { get; set; }
        public decimal Fsar340 { get; set; }
        public decimal Fsar341 { get; set; }
        public decimal Fsar342 { get; set; }
        public decimal Fsar343 { get; set; }
        public decimal Fsar344 { get; set; }
        public decimal Fsar345 { get; set; }
        public decimal Fsar347 { get; set; }
        public decimal Fsar350 { get; set; }
        public decimal Fsar351 { get; set; }
        public decimal Fsar352 { get; set; }
        public decimal Fsar353 { get; set; }
        public decimal Fsar354 { get; set; }
        public decimal Fsar355 { get; set; }
        public decimal Fsar357 { get; set; }
        public decimal Fsar360 { get; set; }
        public decimal Fsar361 { get; set; }
        public decimal Fsar362 { get; set; }
        public decimal Fsar363 { get; set; }
        public decimal Fsar364 { get; set; }
        public decimal Fsar365 { get; set; }
        public decimal Fsar367 { get; set; }
        public decimal Fsar370 { get; set; }
        public decimal Fsar371 { get; set; }
        public decimal Fsar372 { get; set; }
        public decimal Fsar373 { get; set; }
        public decimal Fsar374 { get; set; }
        public decimal Fsar375 { get; set; }
        public decimal Fsar377 { get; set; }
        public decimal Fsar420 { get; set; }
        public decimal Fsar421 { get; set; }
        public decimal Fsar422 { get; set; }
        public decimal Fsar423 { get; set; }
        public decimal Fsar424 { get; set; }
        public decimal Fsar425 { get; set; }
        public decimal Fsar427 { get; set; }
        public decimal Fsar430 { get; set; }
        public decimal Fsar431 { get; set; }
        public decimal Fsar432 { get; set; }
        public decimal Fsar433 { get; set; }
        public decimal Fsar434 { get; set; }
        public decimal Fsar435 { get; set; }
        public decimal Fsar437 { get; set; }
        public decimal Fsar440 { get; set; }
        public decimal Fsar441 { get; set; }
        public decimal Fsar442 { get; set; }
        public decimal Fsar443 { get; set; }
        public decimal Fsar444 { get; set; }
        public decimal Fsar445 { get; set; }
        public decimal Fsar447 { get; set; }
        public decimal Fsar450 { get; set; }
        public decimal Fsar451 { get; set; }
        public decimal Fsar452 { get; set; }
        public decimal Fsar453 { get; set; }
        public decimal Fsar454 { get; set; }
        public decimal Fsar455 { get; set; }
        public decimal Fsar457 { get; set; }
        public decimal Fsar460 { get; set; }
        public decimal Fsar461 { get; set; }
        public decimal Fsar462 { get; set; }
        public decimal Fsar463 { get; set; }
        public decimal Fsar464 { get; set; }
        public decimal Fsar465 { get; set; }
        public decimal Fsar467 { get; set; }
        public decimal Fsar470 { get; set; }
        public decimal Fsar471 { get; set; }
        public decimal Fsar472 { get; set; }
        public decimal Fsar473 { get; set; }
        public decimal Fsar474 { get; set; }
        public decimal Fsar475 { get; set; }
        public decimal Fsar477 { get; set; }
        public decimal Fsar480 { get; set; }
        public decimal Fsar481 { get; set; }
        public decimal Fsar482 { get; set; }
        public decimal Fsar483 { get; set; }
        public decimal Fsar484 { get; set; }
        public decimal Fsar485 { get; set; }
        public decimal Fsar487 { get; set; }
        public decimal Fsar490 { get; set; }
        public decimal Fsar491 { get; set; }
        public decimal Fsar492 { get; set; }
        public decimal Fsar493 { get; set; }
        public decimal Fsar494 { get; set; }
        public decimal Fsar495 { get; set; }
        public decimal Fsar497 { get; set; }
        public int Fsar600 { get; set; }
        public int Fsar601 { get; set; }
        public decimal Fsar603 { get; set; }
        public decimal Fsar604 { get; set; }
        public int Fsar610 { get; set; }
        public int Fsar611 { get; set; }
        public decimal Fsar613 { get; set; }
        public decimal Fsar614 { get; set; }
        public int Fsar620 { get; set; }
        public int Fsar621 { get; set; }
        public decimal Fsar623 { get; set; }
        public decimal Fsar624 { get; set; }
        public int Fsar650 { get; set; }
        public int Fsar651 { get; set; }
        public int Fsar652 { get; set; }
        public int Fsar653 { get; set; }
        public decimal Fsar655 { get; set; }
        public decimal Fsar656 { get; set; }
        public decimal Fsar657 { get; set; }
        public decimal Fsar658 { get; set; }
        public int Fsar660 { get; set; }
        public int Fsar661 { get; set; }
        public int Fsar662 { get; set; }
        public int Fsar663 { get; set; }
        public decimal Fsar665 { get; set; }
        public decimal Fsar666 { get; set; }
        public decimal Fsar667 { get; set; }
        public decimal Fsar668 { get; set; }
        public int Fsar670 { get; set; }
        public int Fsar671 { get; set; }
        public int Fsar672 { get; set; }
        public int Fsar673 { get; set; }
        public decimal Fsar675 { get; set; }
        public decimal Fsar676 { get; set; }
        public decimal Fsar677 { get; set; }
        public decimal Fsar678 { get; set; }
        public int Fsar680 { get; set; }
        public int Fsar681 { get; set; }
        public int Fsar682 { get; set; }
        public int Fsar683 { get; set; }
        public decimal Fsar685 { get; set; }
        public decimal Fsar686 { get; set; }
        public decimal Fsar687 { get; set; }
        public decimal Fsar688 { get; set; }
        public int Fsar720 { get; set; }
        public int Fsar721 { get; set; }
        public decimal Fsar723 { get; set; }
        public decimal Fsar724 { get; set; }
        public decimal Fsar726 { get; set; }
        public int Fsar730 { get; set; }
        public int Fsar731 { get; set; }
        public decimal Fsar733 { get; set; }
        public decimal Fsar734 { get; set; }
        public decimal Fsar736 { get; set; }
        public int Fsar740 { get; set; }
        public int Fsar741 { get; set; }
        public decimal Fsar743 { get; set; }
        public decimal Fsar744 { get; set; }
        public decimal Fsar746 { get; set; }
        public int Fsar750 { get; set; }
        public int Fsar751 { get; set; }
        public decimal Fsar753 { get; set; }
        public decimal Fsar754 { get; set; }
        public decimal Fsar756 { get; set; }
        public int Fsar800 { get; set; }
        public int Fsar801 { get; set; }
        public int Fsar802 { get; set; }
        public int Fsar803 { get; set; }
        public int Fsar804 { get; set; }
        public int Fsar805 { get; set; }
        public int Fsar806 { get; set; }
        public int Fsar807 { get; set; }
        public decimal Fsar810 { get; set; }
        public decimal Fsar811 { get; set; }
        public decimal Fsar812 { get; set; }
        public decimal Fsar813 { get; set; }
        public decimal Fsar814 { get; set; }
        public decimal Fsar815 { get; set; }
        public decimal Fsar816 { get; set; }
        public decimal Fsar817 { get; set; }
        public int Fsar820 { get; set; }
        public int Fsar821 { get; set; }
        public int Fsar822 { get; set; }
        public int Fsar823 { get; set; }
        public int Fsar824 { get; set; }
        public int Fsar825 { get; set; }
        public int Fsar826 { get; set; }
        public int Fsar827 { get; set; }
        public decimal Fsar830 { get; set; }
        public decimal Fsar831 { get; set; }
        public decimal Fsar832 { get; set; }
        public decimal Fsar833 { get; set; }
        public decimal Fsar834 { get; set; }
        public decimal Fsar835 { get; set; }
        public decimal Fsar836 { get; set; }
        public decimal Fsar837 { get; set; }
        public int Fsar840 { get; set; }
        public int Fsar841 { get; set; }
        public int Fsar842 { get; set; }
        public int Fsar843 { get; set; }
        public int Fsar844 { get; set; }
        public int Fsar845 { get; set; }
        public int Fsar846 { get; set; }
        public int Fsar847 { get; set; }
        public decimal Fsar850 { get; set; }
        public decimal Fsar851 { get; set; }
        public decimal Fsar852 { get; set; }
        public decimal Fsar853 { get; set; }
        public decimal Fsar854 { get; set; }
        public decimal Fsar855 { get; set; }
        public decimal Fsar856 { get; set; }
        public decimal Fsar857 { get; set; }
        public int Fsar860 { get; set; }
        public int Fsar861 { get; set; }
        public decimal Fsar865 { get; set; }
        public decimal Fsar866 { get; set; }
        public decimal Fsar951 { get; set; }
        public decimal Fsar952 { get; set; }
        public decimal Fsar953 { get; set; }
        public decimal Fsar955 { get; set; }
        public decimal Fsar957 { get; set; }
        public decimal Fsar959 { get; set; }
        public decimal Fsar960 { get; set; }
        public string Fsar007 { get; set; }
        public int Fsar940 { get; set; }
        public int Fsar941 { get; set; }
        public int Fsar962 { get; set; }
        public decimal Fsar963 { get; set; }
        public decimal Fsar964 { get; set; }
        public decimal Fsar965 { get; set; }
        public int Fsar966 { get; set; }
        public int Fsar967 { get; set; }
        public int Fsar968 { get; set; }
        public int Fsar969 { get; set; }
        public int Fsar970 { get; set; }
        public decimal Fsar971 { get; set; }
        public decimal Fsar972 { get; set; }
        public decimal Fsar973 { get; set; }
        public decimal Fsar974 { get; set; }
        public decimal Fsar975 { get; set; }
        public int Fsar976 { get; set; }
        public decimal Fsar977 { get; set; }
        public int Fsar978 { get; set; }
        public decimal Fsar979 { get; set; }
        public decimal Fsar980 { get; set; }
        public decimal Fsar981 { get; set; }
        public int Fsar982 { get; set; }
        public decimal Fsar983 { get; set; }
        public int Fsar984 { get; set; }
        public decimal Fsar985 { get; set; }
        public int Fsar986 { get; set; }
        public int Fsar987 { get; set; }
        public int Fsar988 { get; set; }
        public int Fsar989 { get; set; }
        public int Fsar990 { get; set; }
        public decimal Fsar991 { get; set; }
        public decimal Fsar992 { get; set; }
        public decimal Fsar993 { get; set; }
        public decimal Fsar994 { get; set; }
        public decimal Fsar995 { get; set; }
        public int Fsar996 { get; set; }
        public int Fsar997 { get; set; }
        public int Fsar998 { get; set; }
        public int Fsar999 { get; set; }
        public int Fsar540 { get; set; }
        public decimal Fsar541 { get; set; }
        public decimal Fsar542 { get; set; }
        public decimal Fsar543 { get; set; }
        public decimal Fsar544 { get; set; }
        public decimal Fsar545 { get; set; }
    }

}
