

namespace Generator
{

    public class KfiDataView
    {
        public int Kfiid { get; set; }
        public string IssueBy { get; set; }
        public string SubBrokerRef { get; set; }
        public int Brokerref { get; set; }
        public string PlanRef { get; set; }
        public string PlanName { get; set; }
        public string PlanFunderRef { get; set; }
        public string Funder { get; set; }
        public string BrokerFirm { get; set; }
        public string BrokerAgentForename { get; set; }
        public string BrokerAgentSurname { get; set; }
        public string BrokerCareOf { get; set; }
        public string BrokerStreet { get; set; }
        public string BrokerDistrict { get; set; }
        public string BrokerTown { get; set; }
        public string BrokerCounty { get; set; }
        public string BrokerPostCode { get; set; }
        public string BrokerFcaNumber { get; set; }
        public string LoanPurpose { get; set; }
        public System.DateTime KfiDate { get; set; }
        public System.DateTime? KfiExpiryDate { get; set; }
        public string KfiType { get; set; }
        public string FullCustomerName { get; set; }
        public string C1Title { get; set; }
        public string C1Forename { get; set; }
        public string C1Surname { get; set; }
        public System.DateTime? C1Dob { get; set; }
        public string C1Gender { get; set; }
        public string C2Title { get; set; }
        public string C2Forename { get; set; }
        public string C2Surname { get; set; }
        public System.DateTime? C2Dob { get; set; }
        public string PropertyType { get; set; }
        public string PropertyConstruction { get; set; }
        public string PropertyMainResidence { get; set; }
        public string PropertyPrivateDwelling { get; set; }
        public string UkResident { get; set; }
        public short CcjNumber { get; set; }
        public decimal CcjValue { get; set; }
        public byte IvaDetails { get; set; }
        public byte BankruptcyDetails { get; set; }
        public decimal NetLoanAmount { get; set; }
        public decimal FeesToBeAdded { get; set; }
        public decimal FeesToBePaid { get; set; }
        public decimal ValuationFee { get; set; }
        public decimal ApplicationFee { get; set; }
        public int ApplicationFeeAddedFlag { get; set; }
        public decimal AcceptanceFee { get; set; }
        public int AcceptanceFeeAddedFlag { get; set; }
        public decimal CompletionFee { get; set; }
        public int CompletionFeeAddedFlag { get; set; }
        public decimal LasiFee { get; set; }
        public int LasiFeeAddedFlag { get; set; }
        public decimal FundTransferFee { get; set; }
        public int FundTransferFeeAddedFlag { get; set; }
        public decimal OtherCompletionFee { get; set; }
        public decimal LoanRedemptionFee { get; set; }
        public decimal SolicitorFee { get; set; }
        public int SolicitorFeeAddedFlag { get; set; }
        public decimal AdvisorFee { get; set; }
        public int AdvisorFeeAddedFlag { get; set; }
        public decimal PropertyValue { get; set; }
        public decimal AprRate { get; set; }
        public decimal GrossLoanAmount { get; set; }
        public decimal TotalAllFees { get; set; }
        public System.DateTime? AcceptanceDate { get; set; }
        public System.DateTime? AppRecvDate { get; set; }
        public int? InternalRefNumber1 { get; set; }
        public int PackagerMortgageId { get; set; }
        public string FriendlyName { get; set; }
        public string BdmName { get; set; }
        public long? RowNumClientBroker { get; set; }
        public long? RowNumClient { get; set; }
        public long? RowNumClientMonth { get; set; }
        public long? RowNumClientWeek { get; set; }
        public long? RowNumClientMonthApp { get; set; }
        public long? RowNumClientWeekApp { get; set; }
        public string AppType { get; set; }
        public string Division { get; set; }
        public string KfiNumber { get; set; }
        public int? PolicyNumber { get; set; }
        public int? AccountNo { get; set; }
        public int? CustomerRef { get; set; }
        public int? AcctRef { get; set; }
        public System.DateTime? DateKfiCreated { get; set; }
        public double? KfiWeek { get; set; }
        public System.DateTime? KfiMonth { get; set; }
        public System.DateTime? DateAppReceived { get; set; }
        public double? AppWeek { get; set; }
        public System.DateTime? AppMonth { get; set; }
        public System.DateTime? OfferIssuedDate { get; set; }
        public double? OfferWeek { get; set; }
        public System.DateTime? OfferMonth { get; set; }
        public System.DateTime? AnticipatedCompletionDate { get; set; }
        public System.DateTime? ActualCompletionDate { get; set; }
        public double? CompWeek { get; set; }
        public System.DateTime? CompMonth { get; set; }
        public int? SingleOrJointApplication { get; set; }
        public string Life1Title { get; set; }
        public string Life1Forename { get; set; }
        public string Life1Surname { get; set; }
        public System.DateTime? Life1Dob { get; set; }
        public string Life1Sex { get; set; }
        public string MaritalStatusLife1 { get; set; }
        public string Life2Title { get; set; }
        public string Life2Forename { get; set; }
        public string Life2Surname { get; set; }
        public System.DateTime? Life2Dob { get; set; }
        public string Life2Sex { get; set; }
        public string MaritalStatusLife2 { get; set; }
        public decimal? EstimatedPropertyValue { get; set; }
        public decimal? SurveyorsPropertyValue { get; set; }
        public System.DateTime? DateOfSurveyorsPropertyValue { get; set; }
        public string ValuationMethod { get; set; }
        public decimal? InitialLoanAmountRequested { get; set; }
        public string ArrangementFeeAddedToLoan { get; set; }
        public decimal? ArrangementFee { get; set; }
        public decimal? InitialLoanRequestedIncFeesAdded { get; set; }
        public decimal? CurrentRetentionBalance { get; set; }
        public decimal? ActualLoanReleasedOnCompletion { get; set; }
        public decimal? RetentionBalanceReleased { get; set; }
        public decimal? TotalLoanReleasedToCustomer { get; set; }
        public decimal? MaximumDrawdownLimit { get; set; }
        public decimal? ChosenDrawdownLimit { get; set; }
        public decimal? DrawdownFacilityAvailableAtCompletion { get; set; }
        public decimal? TotalFacilityAllocatedToCustomerIncludingRetentionsExcludingFees { get; set; }
        public int? DrawdownsMade { get; set; }
        public decimal? DrawdownAmountTaken { get; set; }
        public decimal? RemainingDrawdownFacility { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string District { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public decimal? EstLtv { get; set; }
        public decimal? ActualLtv { get; set; }
        public string FcaNumber { get; set; }
        public decimal? InterestRate { get; set; }
        public string FreeVal { get; set; }
        public string RefundOfValuationFee { get; set; }
        public decimal? Commission { get; set; }
        public decimal? AdviceFee { get; set; }
        public decimal? ContributionToAdviceFee { get; set; }
        public decimal? ContributionToLegalFee { get; set; }
        public string Status { get; set; }
        public System.DateTime? StatusChangeDate { get; set; }
        public string Rejectionreasona { get; set; }
        public string Rejectionreasonb { get; set; }
        public string BrokerClub { get; set; }
        public int? DaysOld { get; set; }
        public string UploadedBy { get; set; }
        public string Underwriter { get; set; }
        public int? InternalRefNumber { get; set; }
        public System.DateTime? WithdrawnDate { get; set; }
        public System.DateTime? RejectedDate { get; set; }
        public decimal? InterestAppliedToDate { get; set; }
        public decimal? InterestDueToBeApplied { get; set; }
        public decimal? RedemptionsToDate { get; set; }
        public string AccountStatus { get; set; }
        public System.DateTime? AccountClosureDate { get; set; }
        public int? BrokerAgentRef { get; set; }
        public string PartialPostcode { get; set; }
        public string OfficialRegion { get; set; }
        public int? Life1Age { get; set; }
        public int? Life2Age { get; set; }
        public int? YoungestAge { get; set; }
        public bool IsFieldBased { get; set; }
        public long? RowNumFirst { get; set; }
    }

}
