

namespace Generator
{

    public class Kfid
    {
        public int Kfid000 { get; set; }
        public string Kfid002 { get; set; }
        public string Kfid004 { get; set; }
        public string Kfid006 { get; set; }
        public int Kfid007 { get; set; }
        public string Kfid008 { get; set; }
        public string Kfid010 { get; set; }
        public byte Kfid011 { get; set; }
        public System.DateTime Kfid018 { get; set; }
        public string Kfid019 { get; set; }
        public System.DateTime Kfid020 { get; set; }
        public System.DateTime Kfid021 { get; set; }
        public byte Kfid022 { get; set; }
        public System.DateTime Kfid024 { get; set; }
        public string Kfid030 { get; set; }
        public string Kfid032 { get; set; }
        public int Kfid040 { get; set; }
        public string Kfid042 { get; set; }
        public string Kfid043 { get; set; }
        public string Kfid044 { get; set; }
        public string Kfid045 { get; set; }
        public string Kfid046 { get; set; }
        public string Kfid047 { get; set; }
        public string Kfid048 { get; set; }
        public string Kfid049 { get; set; }
        public string Kfid050 { get; set; }
        public string Kfid051 { get; set; }
        public string Kfid052 { get; set; }
        public string Kfid053 { get; set; }
        public string Kfid054 { get; set; }
        public string Kfid060 { get; set; }
        public string Kfid070 { get; set; }
        public string Kfid072 { get; set; }
        public string Kfid080 { get; set; }
        public string Kfid081 { get; set; }
        public string Kfid090 { get; set; }
        public string Kfid091 { get; set; }
        public string Kfid092 { get; set; }
        public decimal Kfid100 { get; set; }
        public byte Kfid101 { get; set; }
        public byte Kfid102 { get; set; }
        public decimal Kfid110 { get; set; }
        public string Kfid112 { get; set; }
        public decimal Kfid114 { get; set; }
        public decimal Kfid116 { get; set; }
        public decimal Kfid118 { get; set; }
        public string Kfid120 { get; set; }
        public decimal Kfid130 { get; set; }
        public byte Kfid135 { get; set; }
        public string Kfid137 { get; set; }
        public decimal Kfid140 { get; set; }
        public decimal Kfid141 { get; set; }
        public decimal Kfid142 { get; set; }
        public decimal Kfid143 { get; set; }
        public decimal Kfid150 { get; set; }
        public decimal Kfid151 { get; set; }
        public decimal Kfid152 { get; set; }
        public decimal Kfid153 { get; set; }
        public short Kfid160 { get; set; }
        public short Kfid161 { get; set; }
        public short Kfid165 { get; set; }
        public short Kfid166 { get; set; }
        public string Kfid170 { get; set; }
        public string Kfid205 { get; set; }
        public string Kfid206 { get; set; }
        public decimal Kfid210 { get; set; }
        public decimal Kfid211 { get; set; }
        public string Kfid220 { get; set; }
        public string Kfid230 { get; set; }
        public decimal Kfid240 { get; set; }
        public decimal Kfid245 { get; set; }
        public decimal Kfid250 { get; set; }
        public decimal Kfid255 { get; set; }
        public decimal Kfid260 { get; set; }
        public string Kfid300 { get; set; }
        public string Kfid301 { get; set; }
        public decimal Kfid305 { get; set; }
        public System.DateTime Kfid310 { get; set; }
        public System.DateTime Kfid315 { get; set; }
        public decimal Kfid320 { get; set; }
        public short Kfid322 { get; set; }
        public decimal Kfid324 { get; set; }
        public decimal Kfid326 { get; set; }
        public decimal Kfid330 { get; set; }
        public short Kfid332 { get; set; }
        public decimal Kfid334 { get; set; }
        public decimal Kfid340 { get; set; }
        public short Kfid342 { get; set; }
        public decimal Kfid344 { get; set; }
        public decimal Kfid346 { get; set; }
        public decimal Kfid350 { get; set; }
        public short Kfid352 { get; set; }
        public decimal Kfid354 { get; set; }
        public decimal Kfid3601 { get; set; }
        public decimal Kfid3602 { get; set; }
        public decimal Kfid3603 { get; set; }
        public decimal Kfid3604 { get; set; }
        public decimal Kfid3605 { get; set; }
        public decimal Kfid3606 { get; set; }
        public decimal Kfid3607 { get; set; }
        public short Kfid3651 { get; set; }
        public short Kfid3652 { get; set; }
        public short Kfid3653 { get; set; }
        public short Kfid3654 { get; set; }
        public short Kfid3655 { get; set; }
        public short Kfid3656 { get; set; }
        public short Kfid3657 { get; set; }
        public decimal Kfid400 { get; set; }
        public decimal Kfid401 { get; set; }
        public decimal Kfid410 { get; set; }
        public decimal Kfid411 { get; set; }
        public decimal Kfid412 { get; set; }
        public decimal Kfid413 { get; set; }
        public decimal Kfid414 { get; set; }
        public decimal Kfid415 { get; set; }
        public decimal Kfid416 { get; set; }
        public decimal Kfid417 { get; set; }
        public decimal Kfid419 { get; set; }
        public decimal Kfid420 { get; set; }
        public decimal Kfid421 { get; set; }
        public decimal Kfid450 { get; set; }
        public decimal Kfid455 { get; set; }
        public decimal Kfid4601 { get; set; }
        public decimal Kfid4602 { get; set; }
        public decimal Kfid4603 { get; set; }
        public decimal Kfid4604 { get; set; }
        public decimal Kfid4605 { get; set; }
        public decimal Kfid4606 { get; set; }
        public decimal Kfid4607 { get; set; }
        public decimal Kfid4608 { get; set; }
        public decimal Kfid4609 { get; set; }
        public decimal Kfid46010 { get; set; }
        public short Kfid4651 { get; set; }
        public short Kfid4652 { get; set; }
        public short Kfid4653 { get; set; }
        public short Kfid4654 { get; set; }
        public short Kfid4655 { get; set; }
        public short Kfid4656 { get; set; }
        public short Kfid4657 { get; set; }
        public short Kfid4658 { get; set; }
        public short Kfid4659 { get; set; }
        public short Kfid46510 { get; set; }
        public decimal Kfid4701 { get; set; }
        public decimal Kfid4702 { get; set; }
        public decimal Kfid4703 { get; set; }
        public decimal Kfid4704 { get; set; }
        public decimal Kfid4705 { get; set; }
        public decimal Kfid4706 { get; set; }
        public decimal Kfid4707 { get; set; }
        public decimal Kfid4708 { get; set; }
        public decimal Kfid4709 { get; set; }
        public decimal Kfid47010 { get; set; }
        public short Kfid4751 { get; set; }
        public short Kfid4752 { get; set; }
        public short Kfid4753 { get; set; }
        public short Kfid4754 { get; set; }
        public short Kfid4755 { get; set; }
        public short Kfid4756 { get; set; }
        public short Kfid4757 { get; set; }
        public short Kfid4758 { get; set; }
        public short Kfid4759 { get; set; }
        public short Kfid47510 { get; set; }
        public string Kfid4801 { get; set; }
        public string Kfid4802 { get; set; }
        public string Kfid4803 { get; set; }
        public string Kfid4804 { get; set; }
        public string Kfid4805 { get; set; }
        public string Kfid4806 { get; set; }
        public string Kfid4807 { get; set; }
        public string Kfid4808 { get; set; }
        public string Kfid4809 { get; set; }
        public string Kfid48010 { get; set; }
        public byte Kfid500 { get; set; }
        public decimal Kfid5021 { get; set; }
        public decimal Kfid5022 { get; set; }
        public decimal Kfid5023 { get; set; }
        public decimal Kfid5024 { get; set; }
        public string Kfid504 { get; set; }
        public string Kfid506 { get; set; }
        public decimal Kfid508 { get; set; }
        public string Kfid509 { get; set; }
        public string Kfid516 { get; set; }
        public decimal Kfid518 { get; set; }
        public string Kfid519 { get; set; }
        public decimal Kfid528 { get; set; }
        public string Kfid529 { get; set; }
        public decimal Kfid538 { get; set; }
        public string Kfid539 { get; set; }
        public string Kfid547 { get; set; }
        public decimal Kfid548 { get; set; }
        public decimal Kfid558 { get; set; }
        public decimal Kfid568 { get; set; }
        public string Kfid569 { get; set; }
        public decimal Kfid578 { get; set; }
        public string Kfid579 { get; set; }
        public decimal Kfid590 { get; set; }
        public decimal Kfid591 { get; set; }
        public decimal Kfid592 { get; set; }
        public decimal Kfid593 { get; set; }
        public decimal Kfid594 { get; set; }
        public byte Kfid6501 { get; set; }
        public byte Kfid6502 { get; set; }
        public byte Kfid6503 { get; set; }
        public byte Kfid6504 { get; set; }
        public byte Kfid6505 { get; set; }
        public decimal Kfid6511 { get; set; }
        public decimal Kfid6512 { get; set; }
        public decimal Kfid6513 { get; set; }
        public decimal Kfid6514 { get; set; }
        public decimal Kfid6515 { get; set; }
        public decimal Kfid6521 { get; set; }
        public decimal Kfid6522 { get; set; }
        public decimal Kfid6523 { get; set; }
        public decimal Kfid6524 { get; set; }
        public decimal Kfid6525 { get; set; }
        public decimal Kfid6531 { get; set; }
        public decimal Kfid6532 { get; set; }
        public decimal Kfid6533 { get; set; }
        public decimal Kfid6534 { get; set; }
        public decimal Kfid6535 { get; set; }
        public decimal Kfid6541 { get; set; }
        public decimal Kfid6542 { get; set; }
        public decimal Kfid6543 { get; set; }
        public decimal Kfid6544 { get; set; }
        public decimal Kfid6545 { get; set; }
        public decimal Kfid6551 { get; set; }
        public decimal Kfid6552 { get; set; }
        public decimal Kfid6553 { get; set; }
        public decimal Kfid6554 { get; set; }
        public decimal Kfid6555 { get; set; }
        public decimal Kfid6561 { get; set; }
        public decimal Kfid6562 { get; set; }
        public decimal Kfid6563 { get; set; }
        public decimal Kfid6564 { get; set; }
        public decimal Kfid6565 { get; set; }
        public decimal Kfid6601 { get; set; }
        public decimal Kfid6602 { get; set; }
        public decimal Kfid6603 { get; set; }
        public decimal Kfid6604 { get; set; }
        public decimal Kfid6605 { get; set; }
        public decimal Kfid680 { get; set; }
        public string Kfid795 { get; set; }
        public decimal Kfid800 { get; set; }
        public System.DateTime Kfid950 { get; set; }
        public System.DateTime Kfid952 { get; set; }
        public int Kfid954 { get; set; }
        public string Kfid960 { get; set; }
        public string Kfid965 { get; set; }
        public string Kfid966 { get; set; }
        public string Kfid967 { get; set; }
        public string Kfid970 { get; set; }
        public string Kfid975 { get; set; }
        public int Kfid980 { get; set; }
        public string Kfid580 { get; set; }
        public string Kfid586 { get; set; }
        public decimal Kfid588 { get; set; }
        public string Kfid589 { get; set; }
        public string Kfid055 { get; set; }
        public string Kfid056 { get; set; }
        public string Kfid057 { get; set; }
        public string Kfid058 { get; set; }
        public byte Kfid103 { get; set; }
        public byte Kfid104 { get; set; }
        public byte Kfid105 { get; set; }
        public string Kfid526 { get; set; }
        public int Kfid005 { get; set; }
        public byte Kfid125 { get; set; }
        public string Kfid108 { get; set; }
        public decimal Kfid598 { get; set; }
        public string Kfid599 { get; set; }
        public decimal Kfid610 { get; set; }
        public string Kfid611 { get; set; }
        public byte Kfid106 { get; set; }
        public int Kfid012 { get; set; }
        public short Kfid099 { get; set; }
        public short Kfid113 { get; set; }
        public System.DateTime Kfid0611 { get; set; }
        public System.DateTime Kfid0612 { get; set; }
        public System.DateTime Kfid0613 { get; set; }
        public System.DateTime Kfid0614 { get; set; }
        public string Kfid0621 { get; set; }
        public string Kfid0622 { get; set; }
        public string Kfid0623 { get; set; }
        public string Kfid0624 { get; set; }
        public string Kfid085 { get; set; }
        public string Kfid086 { get; set; }
        public string Kfid065 { get; set; }
        public decimal Kfid235 { get; set; }
        public string Kfid009 { get; set; }
        public decimal Kfid608 { get; set; }
        public int Kfid014 { get; set; }
        public string Kfid996 { get; set; }
        public string Kfid984 { get; set; }
        public int Kfid9851 { get; set; }
        public int Kfid9852 { get; set; }
        public int Kfid9853 { get; set; }
        public int Kfid9854 { get; set; }
        public string Kfid9861 { get; set; }
        public string Kfid9862 { get; set; }
        public string Kfid9863 { get; set; }
        public string Kfid9864 { get; set; }
        public string Kfid9871 { get; set; }
        public string Kfid9872 { get; set; }
        public string Kfid9873 { get; set; }
        public string Kfid9874 { get; set; }
        public decimal Kfid998 { get; set; }
        public decimal Kfid9891 { get; set; }
        public decimal Kfid9892 { get; set; }
        public decimal Kfid9893 { get; set; }
        public decimal Kfid9894 { get; set; }
        public decimal Kfid9901 { get; set; }
        public decimal Kfid9902 { get; set; }
        public decimal Kfid9903 { get; set; }
        public decimal Kfid9904 { get; set; }
        public decimal Kfid991 { get; set; }
        public string Kfid992 { get; set; }
        public string Kfid993 { get; set; }
        public string Kfid994 { get; set; }
        public string Kfid995 { get; set; }
        public string Kfid9971 { get; set; }
        public string Kfid9972 { get; set; }
        public string Kfid9973 { get; set; }
        public string Kfid9974 { get; set; }
        public decimal Kfid6701 { get; set; }
        public decimal Kfid6702 { get; set; }
        public decimal Kfid6703 { get; set; }
        public decimal Kfid6704 { get; set; }
        public decimal Kfid6705 { get; set; }
        public decimal Kfid6711 { get; set; }
        public decimal Kfid6712 { get; set; }
        public decimal Kfid6713 { get; set; }
        public decimal Kfid6714 { get; set; }
        public decimal Kfid6715 { get; set; }
        public decimal Kfid9881 { get; set; }
        public decimal Kfid9882 { get; set; }
        public decimal Kfid9883 { get; set; }
        public decimal Kfid9884 { get; set; }
        public decimal Kfid237 { get; set; }
        public int Kfid207 { get; set; }
        public int Kfid208 { get; set; }
        public decimal Kfid618 { get; set; }
        public decimal Kfid501 { get; set; }
        public decimal Kfid520 { get; set; }
        public string Kfid316 { get; set; }
        public string Kfid098 { get; set; }
        public string Kfid082 { get; set; }
        public string Kfid083 { get; set; }
        public string Kfid084 { get; set; }
        public decimal Kfid801 { get; set; }
        public string Kfid087 { get; set; }
        public string Kfid088 { get; set; }
        public string Kfid802 { get; set; }
        public string Kfid803 { get; set; }
        public int Kfid981 { get; set; }
        public string Kfid982 { get; set; }
        public string Kfid905 { get; set; }
    }

}
