

namespace Generator
{

    public class Lpla
    {
        public int Lpla000 { get; set; }
        public string Lpla010 { get; set; }
        public string Lpla020 { get; set; }
        public byte Lpla030 { get; set; }
        public string Lpla040 { get; set; }
        public System.DateTime Lpla060 { get; set; }
        public System.DateTime Lpla070 { get; set; }
        public string Lpla100 { get; set; }
        public string Lpla105 { get; set; }
        public decimal Lpla115 { get; set; }
        public decimal Lpla120 { get; set; }
        public decimal Lpla125 { get; set; }
        public decimal Lpla130 { get; set; }
        public decimal Lpla135 { get; set; }
        public decimal Lpla200 { get; set; }
        public decimal Lpla210 { get; set; }
        public decimal Lpla225 { get; set; }
        public decimal Lpla235 { get; set; }
        public string Lpla250 { get; set; }
        public decimal Lpla2551 { get; set; }
        public decimal Lpla2552 { get; set; }
        public decimal Lpla2553 { get; set; }
        public decimal Lpla2554 { get; set; }
        public decimal Lpla2555 { get; set; }
        public byte Lpla260 { get; set; }
        public decimal Lpla265 { get; set; }
        public decimal Lpla270 { get; set; }
        public decimal Lpla271 { get; set; }
        public decimal Lpla275 { get; set; }
        public byte Lpla300 { get; set; }
        public byte Lpla305 { get; set; }
        public byte Lpla310 { get; set; }
        public byte Lpla315 { get; set; }
        public byte Lpla320 { get; set; }
        public decimal Lpla400 { get; set; }
        public decimal Lpla405 { get; set; }
        public decimal Lpla4351 { get; set; }
        public decimal Lpla4352 { get; set; }
        public decimal Lpla4353 { get; set; }
        public decimal Lpla4354 { get; set; }
        public decimal Lpla4355 { get; set; }
        public decimal Lpla4356 { get; set; }
        public decimal Lpla4357 { get; set; }
        public decimal Lpla4358 { get; set; }
        public decimal Lpla4401 { get; set; }
        public decimal Lpla4402 { get; set; }
        public decimal Lpla4403 { get; set; }
        public decimal Lpla4404 { get; set; }
        public decimal Lpla4405 { get; set; }
        public decimal Lpla4406 { get; set; }
        public decimal Lpla4407 { get; set; }
        public decimal Lpla4408 { get; set; }
        public decimal Lpla450 { get; set; }
        public decimal Lpla451 { get; set; }
        public decimal Lpla452 { get; set; }
        public string Lpla460 { get; set; }
        public decimal Lpla8001 { get; set; }
        public decimal Lpla8002 { get; set; }
        public decimal Lpla8003 { get; set; }
        public decimal Lpla8004 { get; set; }
        public decimal Lpla8005 { get; set; }
        public decimal Lpla8006 { get; set; }
        public decimal Lpla8007 { get; set; }
        public decimal Lpla8008 { get; set; }
        public decimal Lpla8009 { get; set; }
        public decimal Lpla80010 { get; set; }
        public decimal Lpla80011 { get; set; }
        public decimal Lpla80012 { get; set; }
        public decimal Lpla80013 { get; set; }
        public decimal Lpla80014 { get; set; }
        public decimal Lpla80015 { get; set; }
        public decimal Lpla8051 { get; set; }
        public decimal Lpla8052 { get; set; }
        public decimal Lpla8053 { get; set; }
        public decimal Lpla8054 { get; set; }
        public decimal Lpla8055 { get; set; }
        public decimal Lpla8056 { get; set; }
        public decimal Lpla8057 { get; set; }
        public decimal Lpla8058 { get; set; }
        public decimal Lpla8059 { get; set; }
        public decimal Lpla80510 { get; set; }
        public decimal Lpla80511 { get; set; }
        public decimal Lpla80512 { get; set; }
        public decimal Lpla80513 { get; set; }
        public decimal Lpla80514 { get; set; }
        public decimal Lpla80515 { get; set; }
        public decimal Lpla8101 { get; set; }
        public decimal Lpla8102 { get; set; }
        public decimal Lpla8103 { get; set; }
        public decimal Lpla8104 { get; set; }
        public decimal Lpla8105 { get; set; }
        public decimal Lpla8106 { get; set; }
        public decimal Lpla8107 { get; set; }
        public decimal Lpla8108 { get; set; }
        public decimal Lpla8109 { get; set; }
        public decimal Lpla81010 { get; set; }
        public decimal Lpla81011 { get; set; }
        public decimal Lpla81012 { get; set; }
        public decimal Lpla81013 { get; set; }
        public decimal Lpla81014 { get; set; }
        public decimal Lpla81015 { get; set; }
        public decimal Lpla815 { get; set; }
        public decimal Lpla820 { get; set; }
        public decimal Lpla825 { get; set; }
        public decimal Lpla826 { get; set; }
        public decimal Lpla830 { get; set; }
        public decimal Lpla835 { get; set; }
        public decimal Lpla900 { get; set; }
        public decimal Lpla910 { get; set; }
        public string Lpla920 { get; set; }
        public string Lpla050 { get; set; }
        public string Lpla055 { get; set; }
        public string Lpla056 { get; set; }
        public string Lpla058 { get; set; }
        public string Lpla110 { get; set; }
        public string Lpla111 { get; set; }
        public string Lpla116 { get; set; }
        public string Lpla121 { get; set; }
        public decimal Lpla272 { get; set; }
        public decimal Lpla273 { get; set; }
        public decimal Lpla276 { get; set; }
        public decimal Lpla277 { get; set; }
        public decimal Lpla278 { get; set; }
        public decimal Lpla325 { get; set; }
        public byte Lpla326 { get; set; }
        public byte Lpla330 { get; set; }
        public byte Lpla331 { get; set; }
        public byte Lpla332 { get; set; }
        public byte Lpla335 { get; set; }
        public byte Lpla340 { get; set; }
        public string Lpla410 { get; set; }
        public decimal Lpla415 { get; set; }
        public string Lpla470 { get; set; }
        public decimal Lpla5001 { get; set; }
        public decimal Lpla5002 { get; set; }
        public decimal Lpla5003 { get; set; }
        public decimal Lpla5004 { get; set; }
        public decimal Lpla5005 { get; set; }
        public decimal Lpla5051 { get; set; }
        public decimal Lpla5052 { get; set; }
        public decimal Lpla5053 { get; set; }
        public decimal Lpla5054 { get; set; }
        public decimal Lpla5055 { get; set; }
        public decimal Lpla510 { get; set; }
        public decimal Lpla511 { get; set; }
        public decimal Lpla515 { get; set; }
        public decimal Lpla516 { get; set; }
        public decimal Lpla520 { get; set; }
        public decimal Lpla525 { get; set; }
        public decimal Lpla530 { get; set; }
        public decimal Lpla531 { get; set; }
        public decimal Lpla532 { get; set; }
        public decimal Lpla540 { get; set; }
        public decimal Lpla550 { get; set; }
        public decimal Lpla551 { get; set; }
        public decimal Lpla552 { get; set; }
        public decimal Lpla553 { get; set; }
        public decimal Lpla554 { get; set; }
        public decimal Lpla555 { get; set; }
        public decimal Lpla580 { get; set; }
        public string Lpla581 { get; set; }
        public string Lpla582 { get; set; }
        public string Lpla600 { get; set; }
        public string Lpla605 { get; set; }
        public string Lpla610 { get; set; }
        public string Lpla615 { get; set; }
        public string Lpla620 { get; set; }
        public string Lpla630 { get; set; }
        public string Lpla635 { get; set; }
        public byte Lpla640 { get; set; }
        public string Lpla645 { get; set; }
        public string Lpla650 { get; set; }
        public string Lpla655 { get; set; }
        public byte Lpla680 { get; set; }
        public string Lpla811 { get; set; }
        public string Lpla812 { get; set; }
        public string Lpla821 { get; set; }
        public string Lpla822 { get; set; }
        public string Lpla831 { get; set; }
        public string Lpla832 { get; set; }
        public string Lpla834 { get; set; }
        public string Lpla841 { get; set; }
        public string Lpla842 { get; set; }
        public string Lpla843 { get; set; }
        public string Lpla850 { get; set; }
        public string Lpla851 { get; set; }
        public string Lpla852 { get; set; }
        public string Lpla853 { get; set; }
        public string Lpla861 { get; set; }
        public decimal Lpla880 { get; set; }
        public string Lpla881 { get; set; }
        public string Lpla882 { get; set; }
        public string Lpla891 { get; set; }
        public string Lpla892 { get; set; }
        public decimal Lpla893 { get; set; }
        public decimal Lpla894 { get; set; }
        public decimal Lpla901 { get; set; }
        public decimal Lpla902 { get; set; }
        public decimal Lpla911 { get; set; }
        public decimal Lpla912 { get; set; }
        public string Lpla950 { get; set; }
        public string Lpla955 { get; set; }
        public string Lpla956 { get; set; }
        public byte Lpla960 { get; set; }
        public byte Lpla961 { get; set; }
        public string Lpla965 { get; set; }
        public decimal Lpla8701 { get; set; }
        public decimal Lpla8702 { get; set; }
        public decimal Lpla8703 { get; set; }
        public decimal Lpla8704 { get; set; }
        public decimal Lpla8705 { get; set; }
        public string Lpla871 { get; set; }
        public string Lpla872 { get; set; }
        public decimal Lpla8731 { get; set; }
        public decimal Lpla8732 { get; set; }
        public decimal Lpla8733 { get; set; }
        public decimal Lpla8734 { get; set; }
        public decimal Lpla8735 { get; set; }
        public decimal Lpla8741 { get; set; }
        public decimal Lpla8742 { get; set; }
        public decimal Lpla8743 { get; set; }
        public decimal Lpla8744 { get; set; }
        public decimal Lpla8745 { get; set; }
        public decimal Lpla915 { get; set; }
        public decimal Lpla916 { get; set; }
        public decimal Lpla917 { get; set; }
        public string Lpla329 { get; set; }
        public decimal Lpla845 { get; set; }
        public decimal Lpla846 { get; set; }
        public decimal Lpla847 { get; set; }
        public decimal Lpla848 { get; set; }
        public string Lpla849 { get; set; }
        public decimal Lpla827 { get; set; }
        public decimal Lpla828 { get; set; }
        public decimal Lpla829 { get; set; }
        public byte Lpla333 { get; set; }
        public string Lpla833 { get; set; }
        public string Lpla103 { get; set; }
        public decimal Lpla905 { get; set; }
        public decimal Lpla906 { get; set; }
        public decimal Lpla907 { get; set; }
        public string Lpla075 { get; set; }
        public byte Lpla824 { get; set; }
        public byte Lpla895 { get; set; }
        public short Lpla341 { get; set; }
        public decimal Lpla322 { get; set; }
        public decimal Lpla480 { get; set; }
        public decimal Lpla140 { get; set; }
        public decimal Lpla80016 { get; set; }
        public decimal Lpla80516 { get; set; }
        public decimal Lpla81016 { get; set; }
        public decimal Lpla80017 { get; set; }
        public decimal Lpla80517 { get; set; }
        public decimal Lpla81017 { get; set; }
        public decimal Lpla80018 { get; set; }
        public decimal Lpla80518 { get; set; }
        public decimal Lpla81018 { get; set; }
        public decimal Lpla80019 { get; set; }
        public decimal Lpla80519 { get; set; }
        public decimal Lpla81019 { get; set; }
        public decimal Lpla80020 { get; set; }
        public decimal Lpla80520 { get; set; }
        public decimal Lpla81020 { get; set; }
        public decimal Lpla117 { get; set; }
        public string Lpla145 { get; set; }
        public decimal Lpla560 { get; set; }
        public decimal Lpla565 { get; set; }
        public decimal Lpla685 { get; set; }
        public decimal Lpla690 { get; set; }
        public short Lpla966 { get; set; }
        public short Lpla967 { get; set; }
        public decimal Lpla150 { get; set; }
        public string Lpla651 { get; set; }
        public decimal Lpla3271 { get; set; }
        public decimal Lpla3272 { get; set; }
        public decimal Lpla3273 { get; set; }
        public decimal Lpla3274 { get; set; }
        public decimal Lpla3275 { get; set; }
        public decimal Lpla867 { get; set; }
        public string Lpla868 { get; set; }
        public int Lpla279 { get; set; }
        public int Lpla280 { get; set; }
        public short Lpla290 { get; set; }
        public string Lpla295 { get; set; }
        public byte Lpla323 { get; set; }
        public byte Lpla324 { get; set; }
        public string Lpla862 { get; set; }
        public byte Lpla328 { get; set; }
        public string Lpla836 { get; set; }
        public byte Lpla342 { get; set; }
        public byte Lpla302 { get; set; }
        public byte Lpla307 { get; set; }
        public string Lpla321 { get; set; }
        public short Lpla345 { get; set; }
        public short Lpla346 { get; set; }
        public decimal Lpla813 { get; set; }
        public decimal Lpla883 { get; set; }
        public decimal Lpla896 { get; set; }
        public string Lpla962 { get; set; }
        public decimal Lpla155 { get; set; }
        public decimal Lpla814 { get; set; }
        public decimal Lpla156 { get; set; }
        public string Lpla453 { get; set; }
        public string Lpla454 { get; set; }
        public decimal Lpla455 { get; set; }
        public decimal Lpla456 { get; set; }
        public decimal Lpla457 { get; set; }
        public decimal Lpla458 { get; set; }
        public string Lpla816 { get; set; }
        public string Lpla837 { get; set; }
        public decimal Lpla336 { get; set; }
        public decimal Lpla337 { get; set; }
        public decimal Lpla80021 { get; set; }
        public decimal Lpla80022 { get; set; }
        public decimal Lpla80023 { get; set; }
        public decimal Lpla80024 { get; set; }
        public decimal Lpla80025 { get; set; }
        public decimal Lpla80026 { get; set; }
        public decimal Lpla80027 { get; set; }
        public decimal Lpla80028 { get; set; }
        public decimal Lpla80029 { get; set; }
        public decimal Lpla80030 { get; set; }
        public decimal Lpla80521 { get; set; }
        public decimal Lpla80522 { get; set; }
        public decimal Lpla80523 { get; set; }
        public decimal Lpla80524 { get; set; }
        public decimal Lpla80525 { get; set; }
        public decimal Lpla80526 { get; set; }
        public decimal Lpla80527 { get; set; }
        public decimal Lpla80528 { get; set; }
        public decimal Lpla80529 { get; set; }
        public decimal Lpla80530 { get; set; }
        public decimal Lpla81021 { get; set; }
        public decimal Lpla81022 { get; set; }
        public decimal Lpla81023 { get; set; }
        public decimal Lpla81024 { get; set; }
        public decimal Lpla81025 { get; set; }
        public decimal Lpla81026 { get; set; }
        public decimal Lpla81027 { get; set; }
        public decimal Lpla81028 { get; set; }
        public decimal Lpla81029 { get; set; }
        public decimal Lpla81030 { get; set; }
        public string Lpla461 { get; set; }
        public string Lpla463 { get; set; }
        public decimal Lpla160 { get; set; }
        public decimal Lpla927 { get; set; }
        public decimal Lpla925 { get; set; }
        public decimal Lpla926 { get; set; }
        public string Lpla838 { get; set; }
        public int Lpla147 { get; set; }
        public int Lpla071 { get; set; }
        public System.DateTime Lpla072 { get; set; }
    }

}
