

namespace Generator
{

    public class Nbac
    {
        public int Nbac001 { get; set; }
        public int Nbac002 { get; set; }
        public string Nbac003 { get; set; }
        public string Nbac005 { get; set; }
        public string Nbac006 { get; set; }
        public int Nbac010 { get; set; }
        public int Nbac012 { get; set; }
        public string Nbac014 { get; set; }
        public string Nbac020 { get; set; }
        public string Nbac025 { get; set; }
        public System.DateTime Nbac030 { get; set; }
        public string Nbac040 { get; set; }
        public byte Nbac041 { get; set; }
        public string Nbac050 { get; set; }
        public string Nbac052 { get; set; }
        public int Nbac054 { get; set; }
        public System.DateTime Nbac055 { get; set; }
        public string Nbac060 { get; set; }
        public short Nbac070 { get; set; }
        public short Nbac080 { get; set; }
        public byte Nbac090 { get; set; }
        public short Nbac100 { get; set; }
        public string Nbac110 { get; set; }
        public string Nbac120 { get; set; }
        public int Nbac130 { get; set; }
        public string Nbac140 { get; set; }
        public int Nbac150 { get; set; }
        public int Nbac155 { get; set; }
        public string Nbac160 { get; set; }
        public short Nbac161 { get; set; }
        public decimal Nbac170 { get; set; }
        public decimal Nbac178 { get; set; }
        public System.DateTime Nbac179 { get; set; }
        public decimal Nbac180 { get; set; }
        public string Nbac181 { get; set; }
        public int Nbac182 { get; set; }
        public int Nbac185 { get; set; }
        public short Nbac186 { get; set; }
        public int Nbac187 { get; set; }
        public string Nbac188 { get; set; }
        public byte Nbac189 { get; set; }
        public decimal Nbac190 { get; set; }
        public decimal Nbac192 { get; set; }
        public decimal Nbac200 { get; set; }
        public decimal Nbac205 { get; set; }
        public decimal Nbac206 { get; set; }
        public System.DateTime Nbac207 { get; set; }
        public decimal Nbac210 { get; set; }
        public decimal Nbac215 { get; set; }
        public decimal Nbac217 { get; set; }
        public decimal Nbac220 { get; set; }
        public short Nbac230 { get; set; }
        public decimal Nbac240 { get; set; }
        public decimal Nbac250 { get; set; }
        public string Nbac256 { get; set; }
        public decimal Nbac260 { get; set; }
        public decimal Nbac270 { get; set; }
        public string Nbac280 { get; set; }
        public decimal Nbac285 { get; set; }
        public string Nbac286 { get; set; }
        public decimal Nbac290 { get; set; }
        public int Nbac291 { get; set; }
        public decimal Nbac295 { get; set; }
        public string Nbac296 { get; set; }
        public string Nbac300 { get; set; }
        public string Nbac310 { get; set; }
        public string Nbac320 { get; set; }
        public int Nbac330 { get; set; }
        public int Nbac340 { get; set; }
        public decimal Nbac350 { get; set; }
        public string Nbac360 { get; set; }
        public decimal Nbac370 { get; set; }
        public int Nbac380 { get; set; }
        public short Nbac390 { get; set; }
        public string Nbac400 { get; set; }
        public short Nbac410 { get; set; }
        public string Nbac420 { get; set; }
        public string Nbac430 { get; set; }
        public short Nbac440 { get; set; }
        public string Nbac450 { get; set; }
        public System.DateTime Nbac460 { get; set; }
        public string Nbac500 { get; set; }
        public int Nbac510 { get; set; }
        public string Nbac530 { get; set; }
        public string Nbac540 { get; set; }
        public string Nbac555 { get; set; }
        public System.DateTime Nbac559 { get; set; }
        public int Nbac600 { get; set; }
        public decimal Nbac601 { get; set; }
        public int Nbac605 { get; set; }
        public string Nbac610 { get; set; }
        public string Nbac615 { get; set; }
        public string Nbac620 { get; set; }
        public string Nbac630 { get; set; }
        public string Nbac640 { get; set; }
        public decimal Nbac645 { get; set; }
        public decimal Nbac650 { get; set; }
        public decimal Nbac660 { get; set; }
        public decimal Nbac667 { get; set; }
        public System.DateTime Nbac670 { get; set; }
        public decimal Nbac680 { get; set; }
        public decimal Nbac690 { get; set; }
        public decimal Nbac699 { get; set; }
        public decimal Nbac700 { get; set; }
        public decimal Nbac701 { get; set; }
        public decimal Nbac702 { get; set; }
        public decimal Nbac703 { get; set; }
        public decimal Nbac704 { get; set; }
        public decimal Nbac705 { get; set; }
        public decimal Nbac706 { get; set; }
        public decimal Nbac707 { get; set; }
        public decimal Nbac708 { get; set; }
        public decimal Nbac709 { get; set; }
        public string Nbac710 { get; set; }
        public byte Nbac715 { get; set; }
        public string Nbac720 { get; set; }
        public string Nbac750 { get; set; }
        public int Nbac780 { get; set; }
        public decimal Nbac790 { get; set; }
        public int Nbac800 { get; set; }
        public string Nbac810 { get; set; }
        public string Nbac820 { get; set; }
        public System.DateTime Nbac830 { get; set; }
        public string Nbac860 { get; set; }
        public decimal Nbac870 { get; set; }
        public decimal Nbac880 { get; set; }
        public decimal Nbac890 { get; set; }
        public string Nbac900 { get; set; }
        public System.DateTime Nbac901 { get; set; }
        public System.DateTime Nbac902 { get; set; }
        public short Nbac915 { get; set; }
        public System.DateTime Nbac920 { get; set; }
        public decimal Nbac930 { get; set; }
        public string Nbac935 { get; set; }
        public decimal Nbac940 { get; set; }
        public string Nbac945 { get; set; }
        public int Nbac950 { get; set; }
        public string Nbac951 { get; set; }
        public byte Nbac952 { get; set; }
        public string Nbac953 { get; set; }
        public string Nbac954 { get; set; }
        public string Nbac955 { get; set; }
        public decimal Nbac956 { get; set; }
        public string Nbac965 { get; set; }
        public int Nbac967 { get; set; }
        public string Nbac980 { get; set; }
        public string Nbac981 { get; set; }
        public string Nbac982 { get; set; }
        public string Nbac983 { get; set; }
        public int Nbac984 { get; set; }
        public string Nbac985 { get; set; }
        public string Nbac986 { get; set; }
        public string Nbac987 { get; set; }
        public int Nbac999 { get; set; }
        public int Nbac989 { get; set; }
        public string Nbac888 { get; set; }
        public int Nbac011 { get; set; }
        public System.DateTime Nbac017 { get; set; }
        public string Nbac038 { get; set; }
        public string Nbac048 { get; set; }
        public string Nbac081 { get; set; }
        public decimal Nbac175 { get; set; }
        public string Nbac194 { get; set; }
        public decimal Nbac202 { get; set; }
        public string Nbac261 { get; set; }
        public string Nbac271 { get; set; }
        public decimal Nbac275 { get; set; }
        public string Nbac276 { get; set; }
        public string Nbac311 { get; set; }
        public decimal Nbac355 { get; set; }
        public string Nbac408 { get; set; }
        public int Nbac431 { get; set; }
        public string Nbac507 { get; set; }
        public int Nbac508 { get; set; }
        public string Nbac515 { get; set; }
        public string Nbac517 { get; set; }
        public string Nbac520 { get; set; }
        public string Nbac553 { get; set; }
        public string Nbac565 { get; set; }
        public string Nbac567 { get; set; }
        public short Nbac569 { get; set; }
        public string Nbac571 { get; set; }
        public decimal Nbac580 { get; set; }
        public string Nbac815 { get; set; }
        public string Nbac811 { get; set; }
        public int Nbac822 { get; set; }
        public System.DateTime Nbac825 { get; set; }
        public decimal Nbac827 { get; set; }
        public System.DateTime Nbac835 { get; set; }
        public string Nbac840 { get; set; }
        public decimal Nbac850 { get; set; }
        public decimal Nbac925 { get; set; }
        public string Nbac966 { get; set; }
        public int Nbac990 { get; set; }
        public decimal Nbac184 { get; set; }
        public string Nbac501 { get; set; }
        public decimal Nbac165 { get; set; }
        public string Nbac082 { get; set; }
        public System.DateTime Nbac171 { get; set; }
        public int Nbac949 { get; set; }
        public string Nbac026 { get; set; }
        public string Nbac042 { get; set; }
        public decimal Nbac043 { get; set; }
        public short Nbac044 { get; set; }
        public string Nbac046 { get; set; }
        public short Nbac051 { get; set; }
        public string Nbac988 { get; set; }
        public System.DateTime Nbac208 { get; set; }
        public string Nbac995 { get; set; }
    }

}
