

namespace Generator
{

    public class Orig
    {
        public int Orig001 { get; set; }
        public string Orig004 { get; set; }
        public int Orig005 { get; set; }
        public string Orig008 { get; set; }
        public int Orig010 { get; set; }
        public System.DateTime Orig013 { get; set; }
        public System.DateTime Orig014 { get; set; }
        public System.DateTime Orig015 { get; set; }
        public System.DateTime Orig016 { get; set; }
        public System.DateTime Orig017 { get; set; }
        public System.DateTime Orig018 { get; set; }
        public string Orig020 { get; set; }
        public string Orig035 { get; set; }
        public string Orig036 { get; set; }
        public short Orig0401 { get; set; }
        public short Orig0402 { get; set; }
        public string Orig045 { get; set; }
        public string Orig050 { get; set; }
        public string Orig051 { get; set; }
        public string Orig060 { get; set; }
        public decimal Orig200 { get; set; }
        public decimal Orig202 { get; set; }
        public decimal Orig204 { get; set; }
        public int Orig206 { get; set; }
        public decimal Orig210 { get; set; }
        public decimal Orig215 { get; set; }
        public decimal Orig505 { get; set; }
        public decimal Orig507 { get; set; }
        public byte Orig510 { get; set; }
        public string Orig525 { get; set; }
        public decimal Orig620 { get; set; }
        public string Orig685 { get; set; }
        public int Orig700 { get; set; }
        public byte Orig705 { get; set; }
        public System.DateTime Orig710 { get; set; }
        public string Orig725 { get; set; }
        public decimal Orig530 { get; set; }
        public decimal Orig670 { get; set; }
        public string Orig706 { get; set; }
        public System.DateTime Orig707 { get; set; }
        public string Orig708 { get; set; }
        public System.DateTime Orig709 { get; set; }
        public string Orig801 { get; set; }
        public decimal Orig806 { get; set; }
        public decimal Orig807 { get; set; }
        public decimal Orig808 { get; set; }
        public string Orig809 { get; set; }
        public decimal Orig816 { get; set; }
        public decimal Orig817 { get; set; }
        public decimal Orig818 { get; set; }
        public string Orig819 { get; set; }
        public decimal Orig826 { get; set; }
        public decimal Orig827 { get; set; }
        public decimal Orig828 { get; set; }
        public string Orig829 { get; set; }
        public decimal Orig836 { get; set; }
        public decimal Orig837 { get; set; }
        public decimal Orig838 { get; set; }
        public string Orig839 { get; set; }
        public decimal Orig846 { get; set; }
        public decimal Orig847 { get; set; }
        public decimal Orig848 { get; set; }
        public string Orig849 { get; set; }
        public decimal Orig856 { get; set; }
        public decimal Orig857 { get; set; }
        public decimal Orig858 { get; set; }
        public string Orig859 { get; set; }
        public string Orig882 { get; set; }
        public decimal Orig886 { get; set; }
        public decimal Orig887 { get; set; }
        public decimal Orig888 { get; set; }
        public string Orig889 { get; set; }
        public decimal Orig893 { get; set; }
        public decimal Orig894 { get; set; }
        public decimal Orig895 { get; set; }
        public string Orig011 { get; set; }
        public string Orig012 { get; set; }
        public string Orig058 { get; set; }
        public string Orig515 { get; set; }
        public decimal Orig540 { get; set; }
        public decimal Orig642 { get; set; }
        public decimal Orig680 { get; set; }
        public System.DateTime Orig715 { get; set; }
        public string Orig750 { get; set; }
        public byte Orig802 { get; set; }
        public decimal Orig803 { get; set; }
        public decimal Orig9001 { get; set; }
        public decimal Orig9002 { get; set; }
        public short Orig9051 { get; set; }
        public short Orig9052 { get; set; }
        public string Orig9101 { get; set; }
        public string Orig9102 { get; set; }
        public int Orig9151 { get; set; }
        public int Orig9152 { get; set; }
        public decimal Orig9201 { get; set; }
        public decimal Orig9202 { get; set; }
        public decimal Orig9251 { get; set; }
        public decimal Orig9252 { get; set; }
        public int Orig9301 { get; set; }
        public int Orig9302 { get; set; }
        public decimal Orig9351 { get; set; }
        public decimal Orig9352 { get; set; }
        public decimal Orig790 { get; set; }
        public int Orig025 { get; set; }
        public string Orig026 { get; set; }
        public decimal Orig652 { get; set; }
        public decimal Orig867 { get; set; }
        public decimal Orig868 { get; set; }
        public string Orig869 { get; set; }
        public decimal Orig876 { get; set; }
        public decimal Orig877 { get; set; }
        public decimal Orig878 { get; set; }
        public string Orig879 { get; set; }
        public short Orig070 { get; set; }
        public decimal Orig896 { get; set; }
        public decimal Orig897 { get; set; }
        public decimal Orig898 { get; set; }
        public string Orig899 { get; set; }
        public int Orig052 { get; set; }
        public string Orig053 { get; set; }
        public string Orig054 { get; set; }
        public decimal Orig950 { get; set; }
        public string Orig055 { get; set; }
        public string Orig056 { get; set; }
        public string Orig037 { get; set; }
        public string Orig030 { get; set; }
        public string Orig009 { get; set; }
        public byte Orig125 { get; set; }
        public int Orig007 { get; set; }
        public string Orig711 { get; set; }
        public System.DateTime Orig712 { get; set; }
        public decimal Orig713 { get; set; }
        public decimal Orig714 { get; set; }
        public decimal Orig506 { get; set; }
        public decimal Orig545 { get; set; }
        public int Orig960 { get; set; }
        public string Orig961 { get; set; }
        public int Orig963 { get; set; }
        public System.DateTime Orig964 { get; set; }
        public decimal Orig965 { get; set; }
        public int Orig966 { get; set; }
        public decimal Orig508 { get; set; }
        public byte Orig590 { get; set; }
        public int Orig592 { get; set; }
        public string Orig593 { get; set; }
        public string Orig594 { get; set; }
        public int? Orig595 { get; set; }
        public byte Orig596 { get; set; }
        public byte Orig5971 { get; set; }
        public byte Orig5972 { get; set; }
        public byte Orig5973 { get; set; }
        public byte Orig5974 { get; set; }
        public byte Orig5975 { get; set; }
        public byte Orig5976 { get; set; }
        public byte Orig5977 { get; set; }
        public byte Orig5978 { get; set; }
        public byte Orig5979 { get; set; }
        public byte Orig59710 { get; set; }
        public byte Orig59711 { get; set; }
        public byte Orig59712 { get; set; }
        public int Orig585 { get; set; }
        public string Orig695 { get; set; }
        public System.DateTime Orig970 { get; set; }
        public int Orig975 { get; set; }
        public decimal Orig810 { get; set; }
        public int Orig024 { get; set; }
        public decimal Orig600 { get; set; }
        public decimal Orig601 { get; set; }
        public decimal Orig201 { get; set; }
        public decimal Orig203 { get; set; }
        public decimal Orig205 { get; set; }
        public decimal Orig207 { get; set; }
        public decimal Orig208 { get; set; }
        public decimal Orig216 { get; set; }
        public decimal Orig217 { get; set; }
        public decimal Orig218 { get; set; }
        public decimal Orig219 { get; set; }
        public string Orig300 { get; set; }
        public System.DateTime Orig302 { get; set; }
        public string Orig310 { get; set; }
        public System.DateTime Orig312 { get; set; }
        public string Orig320 { get; set; }
        public System.DateTime Orig340 { get; set; }
        public decimal Orig509 { get; set; }
        public decimal Orig760 { get; set; }
        public decimal Orig765 { get; set; }
        public string Orig770 { get; set; }
        public decimal Orig825 { get; set; }
        public decimal Orig865 { get; set; }
        public System.DateTime Orig019 { get; set; }
        public byte Orig305 { get; set; }
        public string Orig341 { get; set; }
        public byte Orig703 { get; set; }
        public string Orig980 { get; set; }
        public byte Orig199 { get; set; }
        public string Orig031 { get; set; }
        public string Orig511 { get; set; }
        public string Orig021 { get; set; }
        public string Orig985 { get; set; }
        public decimal Orig602 { get; set; }
        public decimal Orig209 { get; set; }
        public System.DateTime Orig027 { get; set; }
        public decimal Orig860 { get; set; }
        public decimal Orig504 { get; set; }
        public decimal Orig861 { get; set; }
        public decimal Orig862 { get; set; }
        public decimal Orig863 { get; set; }
        public string Orig864 { get; set; }
        public decimal Orig870 { get; set; }
        public System.DateTime Orig560 { get; set; }
        public string Orig955 { get; set; }
        public decimal Orig820 { get; set; }
        public decimal Orig830 { get; set; }
        public string Orig986 { get; set; }
        public byte Orig542 { get; set; }
        public decimal Orig543 { get; set; }
        public byte Orig065 { get; set; }
        public System.DateTime Orig716 { get; set; }
        public byte Orig795 { get; set; }
        public string Orig720 { get; set; }
        public string Orig049 { get; set; }
        public string Orig048 { get; set; }
        public string Orig850 { get; set; }
        public int Orig852 { get; set; }
        public decimal Orig660 { get; set; }
        public decimal Orig831 { get; set; }
        public string Orig081 { get; set; }
        public decimal Orig570 { get; set; }
        public byte Orig041 { get; set; }
        public decimal Orig880 { get; set; }
        public short Orig957 { get; set; }
        public System.DateTime Orig022 { get; set; }
        public System.DateTime Orig956 { get; set; }
        public string Orig221 { get; set; }
        public string Orig976 { get; set; }
        public string Orig046 { get; set; }
        public decimal Orig538 { get; set; }
        public decimal Orig539 { get; set; }
        public byte Orig855 { get; set; }
    }

}
