

namespace Generator
{

    public class Per
    {
        public int Pers010 { get; set; }
        public byte Pers015 { get; set; }
        public int Pers020 { get; set; }
        public System.DateTime Pers040 { get; set; }
        public System.DateTime Pers050 { get; set; }
        public string Pers060 { get; set; }
        public string Pers080 { get; set; }
        public string Pers090 { get; set; }
        public string Pers091 { get; set; }
        public string Pers092 { get; set; }
        public decimal Pers1001 { get; set; }
        public decimal Pers1002 { get; set; }
        public decimal Pers1003 { get; set; }
        public decimal Pers1004 { get; set; }
        public decimal Pers1005 { get; set; }
        public string Pers1101 { get; set; }
        public string Pers1102 { get; set; }
        public string Pers1103 { get; set; }
        public string Pers1104 { get; set; }
        public string Pers1105 { get; set; }
        public System.DateTime Pers120 { get; set; }
        public System.DateTime Pers140 { get; set; }
        public string Pers170 { get; set; }
        public string Pers210 { get; set; }
        public decimal Pers220 { get; set; }
        public decimal Pers225 { get; set; }
        public System.DateTime Pers230 { get; set; }
        public string Pers240 { get; set; }
        public string Pers160 { get; set; }
        public string Pers180 { get; set; }
        public int Numkey { get; set; }
        public byte[] Persdtm { get; private set; }
        public string Pers055 { get; set; }
        public string Pers057 { get; set; }
        public string Pers400 { get; set; }
        public string Pers070 { get; set; }
        public byte Pers095 { get; set; }
        public string Pers112 { get; set; }
        public string Pers114 { get; set; }
        public decimal Pers125 { get; set; }
        public decimal Pers130 { get; set; }
        public decimal Pers135 { get; set; }
        public System.DateTime Pers145 { get; set; }
        public short Pers150 { get; set; }
        public string Pers165 { get; set; }
        public string Pers190 { get; set; }
        public string Pers450 { get; set; }
        public string Pers500 { get; set; }
        public string Pers510 { get; set; }
        public string Pers520 { get; set; }
        public string Pers600 { get; set; }
        public int Pers610 { get; set; }
        public string Pers530 { get; set; }
        public byte Pers051 { get; set; }
        public string Pers056 { get; set; }
        public System.DateTime Pers041 { get; set; }
        public string Pers1011 { get; set; }
        public string Pers1012 { get; set; }
        public string Pers1013 { get; set; }
        public string Pers1014 { get; set; }
        public string Pers1015 { get; set; }
        public string Pers162 { get; set; }
        public decimal Pers1006 { get; set; }
        public decimal Pers1007 { get; set; }
        public decimal Pers1008 { get; set; }
        public decimal Pers1009 { get; set; }
        public decimal Pers10010 { get; set; }
        public string Pers1016 { get; set; }
        public string Pers1017 { get; set; }
        public string Pers1018 { get; set; }
        public string Pers1019 { get; set; }
        public string Pers10110 { get; set; }
        public string Pers1106 { get; set; }
        public string Pers1107 { get; set; }
        public string Pers1108 { get; set; }
        public string Pers1109 { get; set; }
        public string Pers11010 { get; set; }
        public string Pers200 { get; set; }
        public int Pers205 { get; set; }
        public System.DateTime Pers042 { get; set; }
        public string Pers740 { get; set; }
        public string Pers742 { get; set; }
        public string Pers745 { get; set; }
        public string Pers747 { get; set; }
        public string Pers751 { get; set; }
        public string Pers550 { get; set; }
        public string Pers555 { get; set; }
        public byte Pers560 { get; set; }
        public int Pers565 { get; set; }
        public System.DateTime Pers567 { get; set; }
        public string Pers093 { get; set; }
        public int Pers096 { get; set; }
        public string Pers360 { get; set; }
        public System.DateTime Pers290 { get; set; }
        public short Pers365 { get; set; }
        public short Pers097 { get; set; }
        public short Pers370 { get; set; }
        public System.DateTime Pers535 { get; set; }
        public string Pers375 { get; set; }
        public decimal Pers017 { get; set; }
        public System.DateTime Pers044 { get; set; }
        public string Pers098 { get; set; }
        public string Pers460 { get; set; }
        public string Pers470 { get; set; }
        public System.DateTime Pers043 { get; set; }
        public decimal Pers105 { get; set; }
        public string Pers215 { get; set; }
        public byte Pers071 { get; set; }
        public string Pers075 { get; set; }
        public string Pers078 { get; set; }
        public string Pers079 { get; set; }
        public string Pers195 { get; set; }
        public System.DateTime Pers196 { get; set; }
        public string Pers197 { get; set; }
        public string Pers380 { get; set; }
        public string Pers385 { get; set; }
        public string Pers390 { get; set; }
        public byte Pers490 { get; set; }
        public string Pers491 { get; set; }
        public System.DateTime Pers800 { get; set; }
        public int Pers801 { get; set; }
        public string Pers166 { get; set; }
        public string Pers760 { get; set; }
        public string Pers175 { get; set; }
        public string Pers076 { get; set; }
    }

}
