

namespace Generator
{

    public class Prap
    {
        public int Prap010 { get; set; }
        public string Prap015 { get; set; }
        public int Prap020 { get; set; }
        public string Prap025 { get; set; }
        public string Prap030 { get; set; }
        public string Prap035 { get; set; }
        public System.DateTime Prap040 { get; set; }
        public System.DateTime Prap050 { get; set; }
        public System.DateTime Prap090 { get; set; }
        public string Prap095 { get; set; }
        public int Prap100 { get; set; }
        public string Prap105 { get; set; }
        public string Prap110 { get; set; }
        public string Prap115 { get; set; }
        public string Prap120 { get; set; }
        public string Prap125 { get; set; }
        public string Prap190 { get; set; }
        public string Prap200 { get; set; }
        public string Prap201 { get; set; }
        public string Prap202 { get; set; }
        public string Prap203 { get; set; }
        public string Prap204 { get; set; }
        public string Prap205 { get; set; }
        public string Prap208 { get; set; }
        public int Prap210 { get; set; }
        public decimal Prap212 { get; set; }
        public decimal Prap213 { get; set; }
        public System.DateTime Prap214 { get; set; }
        public string Prap215 { get; set; }
        public int Prap216 { get; set; }
        public int Prap217 { get; set; }
        public short Prap218 { get; set; }
        public byte Prap219 { get; set; }
        public short Prap220 { get; set; }
        public short Prap225 { get; set; }
        public decimal Prap230 { get; set; }
        public decimal Prap235 { get; set; }
        public short Prap250 { get; set; }
        public short Prap255 { get; set; }
        public decimal Prap260 { get; set; }
        public decimal Prap265 { get; set; }
        public string Prap290 { get; set; }
        public decimal Prap312 { get; set; }
        public decimal Prap313 { get; set; }
        public System.DateTime Prap314 { get; set; }
        public int Prap316 { get; set; }
        public decimal Prap330 { get; set; }
        public decimal Prap335 { get; set; }
        public short Prap350 { get; set; }
        public short Prap355 { get; set; }
        public decimal Prap360 { get; set; }
        public decimal Prap365 { get; set; }
        public string Prap390 { get; set; }
        public string Prap500 { get; set; }
        public decimal Prap505 { get; set; }
        public byte Prap510 { get; set; }
        public short Prap520 { get; set; }
        public string Prap525 { get; set; }
        public decimal Prap620 { get; set; }
        public string Prap700 { get; set; }
        public short Prap7051 { get; set; }
        public short Prap7052 { get; set; }
        public string Prap710 { get; set; }
        public string Prap715 { get; set; }
        public int Prap720 { get; set; }
        public string Prap725 { get; set; }
        public string Prap112 { get; set; }
        public string Prap209 { get; set; }
        public System.DateTime Prap211 { get; set; }
        public System.DateTime Prap228 { get; set; }
        public string Prap712 { get; set; }
        public int Prap516 { get; set; }
        public string Prap556 { get; set; }
        public int Prap730 { get; set; }
        public int Prap721 { get; set; }
        public byte Prap012 { get; set; }
        public string Prap080 { get; set; }
        public string Prap085 { get; set; }
        public decimal Prap280 { get; set; }
        public decimal Prap380 { get; set; }
        public int Prap722 { get; set; }
        public string Prap127 { get; set; }
        public string Prap735 { get; set; }
        public int Prap713 { get; set; }
        public System.DateTime Prap800 { get; set; }
        public int Prap001 { get; set; }
        public int Prap046 { get; set; }
        public int Prap021 { get; set; }
        public string Prap026 { get; set; }
        public string Prap031 { get; set; }
        public string Prap081 { get; set; }
        public string Prap082 { get; set; }
        public decimal Prap660 { get; set; }
        public decimal Prap661 { get; set; }
        public decimal Prap662 { get; set; }
        public decimal Prap663 { get; set; }
        public decimal Prap664 { get; set; }
        public System.DateTime Prap666 { get; set; }
        public int Prap087 { get; set; }
        public int Prap810 { get; set; }
        public System.DateTime Prap820 { get; set; }
    }

}
