

namespace Generator
{

    public class Prod
    {
        public int Prod000 { get; set; }
        public int Prod001 { get; set; }
        public string Prod010 { get; set; }
        public string Prod015 { get; set; }
        public string Prod020 { get; set; }
        public System.DateTime Prod030 { get; set; }
        public System.DateTime Prod032 { get; set; }
        public string Prod034 { get; set; }
        public string Prod050 { get; set; }
        public string Prod060 { get; set; }
        public string Prod100 { get; set; }
        public string Prod200 { get; set; }
        public decimal Prod210 { get; set; }
        public decimal Prod220 { get; set; }
        public string Prod250 { get; set; }
        public string Prod260 { get; set; }
        public string Prod300 { get; set; }
        public short Prod350 { get; set; }
        public string Prod360 { get; set; }
        public string Prod370 { get; set; }
        public string Prod400 { get; set; }
        public string Prod500 { get; set; }
        public string Prod700 { get; set; }
        public string Prod710 { get; set; }
        public decimal Prod720 { get; set; }
        public short Prod730 { get; set; }
        public decimal Prod740 { get; set; }
        public string Prod110 { get; set; }
        public decimal Prod115 { get; set; }
        public string Prod120 { get; set; }
        public byte Prod125 { get; set; }
        public System.DateTime Prod127 { get; set; }
        public decimal Prod130 { get; set; }
        public string Prod135 { get; set; }
        public string Prod140 { get; set; }
        public decimal Prod280 { get; set; }
        public string Prod285 { get; set; }
        public string Prod600 { get; set; }
        public decimal Prod6051 { get; set; }
        public decimal Prod6052 { get; set; }
        public decimal Prod6053 { get; set; }
        public decimal Prod6054 { get; set; }
        public decimal Prod6055 { get; set; }
        public short Prod6101 { get; set; }
        public short Prod6102 { get; set; }
        public short Prod6103 { get; set; }
        public short Prod6104 { get; set; }
        public short Prod6105 { get; set; }
        public System.DateTime Prod6151 { get; set; }
        public System.DateTime Prod6152 { get; set; }
        public System.DateTime Prod6153 { get; set; }
        public System.DateTime Prod6154 { get; set; }
        public System.DateTime Prod6155 { get; set; }
        public decimal Prod620 { get; set; }
        public decimal Prod625 { get; set; }
        public string Prod005 { get; set; }
        public byte Prod800 { get; set; }
        public string Prod810 { get; set; }
        public decimal Prod450 { get; set; }
        public decimal Prod460 { get; set; }
        public byte Prod182 { get; set; }
        public decimal Prod184 { get; set; }
        public byte Prod188 { get; set; }
        public byte Prod630 { get; set; }
        public string Prod635 { get; set; }
        public byte Prod640 { get; set; }
        public string Prod645 { get; set; }
        public string Prod650 { get; set; }
        public string Prod655 { get; set; }
        public string Prod660 { get; set; }
        public string Prod185 { get; set; }
        public decimal Prod920 { get; set; }
        public decimal Prod930 { get; set; }
        public byte Prod940 { get; set; }
        public string Prod950 { get; set; }
        public string Prod105 { get; set; }
        public decimal Prod1161 { get; set; }
        public decimal Prod1162 { get; set; }
        public decimal Prod1163 { get; set; }
        public decimal Prod1164 { get; set; }
        public decimal Prod1165 { get; set; }
        public decimal Prod1171 { get; set; }
        public decimal Prod1172 { get; set; }
        public decimal Prod1173 { get; set; }
        public decimal Prod1174 { get; set; }
        public decimal Prod1175 { get; set; }
        public decimal Prod118 { get; set; }
        public decimal Prod119 { get; set; }
        public System.DateTime Prod123 { get; set; }
        public System.DateTime Prod124 { get; set; }
        public System.DateTime Prod126 { get; set; }
        public byte Prod275 { get; set; }
        public decimal Prod510 { get; set; }
        public string Prod515 { get; set; }
        public byte Prod520 { get; set; }
        public string Prod617 { get; set; }
        public decimal Prod618 { get; set; }
        public short Prod354 { get; set; }
        public string Prod352 { get; set; }
        public string Prod111 { get; set; }
        public string Prod136 { get; set; }
        public decimal Prod530 { get; set; }
        public decimal Prod150 { get; set; }
        public decimal Prod1511 { get; set; }
        public decimal Prod1512 { get; set; }
        public decimal Prod1513 { get; set; }
        public decimal Prod1514 { get; set; }
        public decimal Prod1515 { get; set; }
        public decimal Prod155 { get; set; }
        public decimal Prod1561 { get; set; }
        public decimal Prod1562 { get; set; }
        public decimal Prod1563 { get; set; }
        public decimal Prod1564 { get; set; }
        public decimal Prod1565 { get; set; }
        public decimal Prod160 { get; set; }
        public decimal Prod1611 { get; set; }
        public decimal Prod1612 { get; set; }
        public decimal Prod1613 { get; set; }
        public decimal Prod1614 { get; set; }
        public decimal Prod1615 { get; set; }
        public decimal Prod165 { get; set; }
        public decimal Prod1661 { get; set; }
        public decimal Prod1662 { get; set; }
        public decimal Prod1663 { get; set; }
        public decimal Prod1664 { get; set; }
        public decimal Prod1665 { get; set; }
        public string Prod531 { get; set; }
        public string Prod145 { get; set; }
        public decimal Prod525 { get; set; }
        public byte Prod104 { get; set; }
        public string Prod106 { get; set; }
        public int Prod850 { get; set; }
        public string Prod550 { get; set; }
        public decimal Prod555 { get; set; }
        public decimal Prod290 { get; set; }
        public short Prod6121 { get; set; }
        public short Prod6122 { get; set; }
        public short Prod6123 { get; set; }
        public short Prod6124 { get; set; }
        public short Prod6125 { get; set; }
        public int Prod190 { get; set; }
        public string Prod860 { get; set; }
        public string Prod865 { get; set; }
        public int Prod007 { get; set; }
        public byte Prod859 { get; set; }
        public byte Prod861 { get; set; }
        public byte Prod864 { get; set; }
        public byte Prod870 { get; set; }
        public byte Prod871 { get; set; }
        public byte Prod874 { get; set; }
        public byte Prod880 { get; set; }
        public byte Prod890 { get; set; }
        public byte Prod892 { get; set; }
        public decimal Prod1391 { get; set; }
        public decimal Prod1392 { get; set; }
        public decimal Prod1393 { get; set; }
        public decimal Prod1394 { get; set; }
        public decimal Prod1395 { get; set; }
        public short Prod138 { get; set; }
        public byte Prod857 { get; set; }
        public byte Prod858 { get; set; }
        public decimal Prod170 { get; set; }
        public decimal Prod1711 { get; set; }
        public decimal Prod1712 { get; set; }
        public decimal Prod1713 { get; set; }
        public decimal Prod1714 { get; set; }
        public decimal Prod1715 { get; set; }
        public short Prod6161 { get; set; }
        public short Prod6162 { get; set; }
        public short Prod6163 { get; set; }
        public short Prod6164 { get; set; }
        public short Prod6165 { get; set; }
        public int Prod670 { get; set; }
        public string Prod075 { get; set; }
        public string Prod987 { get; set; }
        public string Prod989 { get; set; }
        public decimal Prod990 { get; set; }
        public string Prod991 { get; set; }
        public string Prod080 { get; set; }
        public decimal Prod175 { get; set; }
        public short Prod144 { get; set; }
        public string Prod070 { get; set; }
        public decimal Prod1166 { get; set; }
        public decimal Prod1167 { get; set; }
        public decimal Prod1168 { get; set; }
        public decimal Prod1176 { get; set; }
        public decimal Prod1177 { get; set; }
        public decimal Prod1178 { get; set; }
        public decimal Prod1396 { get; set; }
        public decimal Prod1397 { get; set; }
        public decimal Prod1398 { get; set; }
        public decimal Prod1666 { get; set; }
        public decimal Prod1667 { get; set; }
        public decimal Prod1668 { get; set; }
        public decimal Prod1716 { get; set; }
        public decimal Prod1717 { get; set; }
        public decimal Prod1718 { get; set; }
        public string Prod988 { get; set; }
        public string Prod305 { get; set; }
        public short Prod310 { get; set; }
        public string Prod372 { get; set; }
        public decimal Prod480 { get; set; }
        public decimal Prod107 { get; set; }
        public byte Prod108 { get; set; }
        public byte Prod109 { get; set; }
        public byte Prod365 { get; set; }
        public string Prod366 { get; set; }
        public byte Prod102 { get; set; }
        public string Prod255 { get; set; }
        public short Prod257 { get; set; }
        public int Prod410 { get; set; }
        public string Prod560 { get; set; }
        public string Prod570 { get; set; }
        public string Prod412 { get; set; }
        public string Prod148 { get; set; }
        public string Prod375 { get; set; }
        public int Prod376 { get; set; }
        public byte Prod377 { get; set; }
        public string Prod801 { get; set; }
        public string Prod071 { get; set; }
        public string Prod085 { get; set; }
        public string Prod090 { get; set; }
        public short Prod121 { get; set; }
        public short Prod146 { get; set; }
        public byte Prod195 { get; set; }
        public decimal Prod295 { get; set; }
        public string Prod296 { get; set; }
        public decimal Prod367 { get; set; }
        public int Prod368 { get; set; }
        public int Prod369 { get; set; }
        public byte Prod371 { get; set; }
        public string Prod373 { get; set; }
        public string Prod374 { get; set; }
        public decimal Prod413 { get; set; }
        public string Prod180 { get; set; }
        public byte Prod380 { get; set; }
        public string Prod381 { get; set; }
        public string Prod382 { get; set; }
        public string Prod867 { get; set; }
        public string Prod580 { get; set; }
        public string Prod900 { get; set; }
        public System.DateTime Prod122 { get; set; }
        public string Prod340 { get; set; }
        public string Prod901 { get; set; }
        public int Prod902 { get; set; }
        public int Prod401 { get; set; }
        public System.DateTime Prod402 { get; set; }
        public string Prod992 { get; set; }
        public string Prod006 { get; set; }
        public string Prod993 { get; set; }
    }

}
