

namespace Generator
{

    public class Prsa
    {
        public string Prsa004 { get; set; }
        public int Prsa010 { get; set; }
        public string Prsa020 { get; set; }
        public byte Prsa032 { get; set; }
        public short Prsa035 { get; set; }
        public short Prsa040 { get; set; }
        public string Prsa045 { get; set; }
        public short Prsa049 { get; set; }
        public short Prsa054 { get; set; }
        public short Prsa056 { get; set; }
        public short Prsa058 { get; set; }
        public string Prsa059 { get; set; }
        public string Prsa061 { get; set; }
        public short Prsa062 { get; set; }
        public short Prsa064 { get; set; }
        public short Prsa065 { get; set; }
        public short Prsa066 { get; set; }
        public short Prsa067 { get; set; }
        public string Prsa069 { get; set; }
        public string Prsa071 { get; set; }
        public string Prsa072 { get; set; }
        public string Prsa073 { get; set; }
        public string Prsa074 { get; set; }
        public int Prsa075 { get; set; }
        public int Prsa076 { get; set; }
        public int Prsa077 { get; set; }
        public byte Prsa078 { get; set; }
        public byte Prsa079 { get; set; }
        public int Prsa080 { get; set; }
        public string Prsa085 { get; set; }
        public System.DateTime Prsa122 { get; set; }
        public decimal Prsa124 { get; set; }
        public decimal Prsa128 { get; set; }
        public decimal Prsa129 { get; set; }
        public decimal Prsa131 { get; set; }
        public decimal Prsa132 { get; set; }
        public decimal Prsa133 { get; set; }
        public int Prsa136 { get; set; }
        public string Prsa165 { get; set; }
        public string Prsa170 { get; set; }
        public decimal Prsa175 { get; set; }
        public string Prsa176 { get; set; }
        public decimal Prsa265 { get; set; }
        public decimal Prsa270 { get; set; }
        public decimal Prsa280 { get; set; }
        public int Prsa290 { get; set; }
        public System.DateTime Prsa295 { get; set; }
        public string Prsa305 { get; set; }
        public int Prsa310 { get; set; }
        public int Prsa315 { get; set; }
        public int Prsa320 { get; set; }
        public int Prsa325 { get; set; }
        public string Prsa481 { get; set; }
        public string Prsa482 { get; set; }
        public string Prsa483 { get; set; }
        public short Prsa485 { get; set; }
        public string Prsa490 { get; set; }
        public short Prsa510 { get; set; }
        public decimal Prsa570 { get; set; }
        public System.DateTime Prsa575 { get; set; }
        public string Prsa600 { get; set; }
        public short Prsa650 { get; set; }
        public short Prsa655 { get; set; }
        public int Prsa660 { get; set; }
        public string Prsa665 { get; set; }
        public string Prsa670 { get; set; }
        public string Prsa675 { get; set; }
        public string Prsa680 { get; set; }
        public System.DateTime Prsa685 { get; set; }
        public string Prsa690 { get; set; }
        public int Prsa700 { get; set; }
        public short Prsa705 { get; set; }
        public decimal Prsa710 { get; set; }
        public decimal Prsa715 { get; set; }
        public decimal Prsa720 { get; set; }
        public decimal Prsa725 { get; set; }
        public System.DateTime Prsa123 { get; set; }
        public string Prsa063 { get; set; }
        public string Prsa550 { get; set; }
        public string Prsa555 { get; set; }
        public string Prsa557 { get; set; }
        public short Prsa330 { get; set; }
        public short Prsa340 { get; set; }
        public string Prsa350 { get; set; }
        public System.DateTime Prsa360 { get; set; }
        public decimal Prsa370 { get; set; }
        public string Prsa380 { get; set; }
        public string Prsa930 { get; set; }
        public byte Prsa940 { get; set; }
        public string Prsa950 { get; set; }
        public byte Prsa990 { get; set; }
        public decimal Prsa995 { get; set; }
        public decimal Prsa970 { get; set; }
        public decimal Prsa975 { get; set; }
        public decimal Prsa960 { get; set; }
        public decimal Prsa965 { get; set; }
        public decimal Prsa204 { get; set; }
        public decimal Prsa205 { get; set; }
        public decimal Prsa206 { get; set; }
        public decimal Prsa207 { get; set; }
        public decimal Prsa209 { get; set; }
        public decimal Prsa212 { get; set; }
        public decimal Prsa216 { get; set; }
        public decimal Prsa217 { get; set; }
        public decimal Prsa231 { get; set; }
        public decimal Prsa232 { get; set; }
        public decimal Prsa233 { get; set; }
        public decimal Prsa234 { get; set; }
        public short Prsa057 { get; set; }
        public short Prsa560 { get; set; }
        public short Prsa068 { get; set; }
        public short Prsa070 { get; set; }
        public decimal Prsa260 { get; set; }
        public decimal Prsa261 { get; set; }
        public decimal Prsa262 { get; set; }
        public decimal Prsa211 { get; set; }
        public System.DateTime Prsa980 { get; set; }
        public System.DateTime Prsa981 { get; set; }
        public short Prsa982 { get; set; }
        public System.DateTime Prsa983 { get; set; }
        public System.DateTime Prsa984 { get; set; }
        public byte Prsa985 { get; set; }
        public string Prsa055 { get; set; }
        public decimal Prsa083 { get; set; }
        public decimal Prsa084 { get; set; }
        public decimal Prsa218 { get; set; }
        public decimal Prsa263 { get; set; }
        public string Prsa695 { get; set; }
        public string Prsa696 { get; set; }
        public string Prsa698 { get; set; }
        public string Prsa326 { get; set; }
        public string Prsa678 { get; set; }
        public decimal Prsa241 { get; set; }
        public decimal Prsa285 { get; set; }
        public System.DateTime Prsa286 { get; set; }
        public decimal Prsa327 { get; set; }
        public string Prsa677 { get; set; }
        public decimal Prsa328 { get; set; }
        public int Prsa699 { get; set; }
        public string Prsa037 { get; set; }
        public decimal Prsa287 { get; set; }
        public decimal Prsa281 { get; set; }
        public decimal Prsa282 { get; set; }
        public string Prsa750 { get; set; }
        public System.DateTime Prsa284 { get; set; }
        public System.DateTime Prsa288 { get; set; }
        public System.DateTime Prsa289 { get; set; }
        public decimal Prsa283 { get; set; }
        public System.DateTime Prsa291 { get; set; }
    }

}
