

namespace Generator
{

    public class Quot
    {
        public int Quot999 { get; set; }
        public int Quot010 { get; set; }
        public System.DateTime Quot020 { get; set; }
        public string Quot030 { get; set; }
        public System.DateTime Quot040 { get; set; }
        public string Quot050 { get; set; }
        public byte Quot060 { get; set; }
        public int Quot070 { get; set; }
        public byte Quot080 { get; set; }
        public byte Quot085 { get; set; }
        public decimal Quot090 { get; set; }
        public decimal Quot100 { get; set; }
        public decimal Quot105 { get; set; }
        public decimal Quot110 { get; set; }
        public decimal Quot120 { get; set; }
        public decimal Quot130 { get; set; }
        public decimal Quot135 { get; set; }
        public decimal Quot140 { get; set; }
        public decimal Quot145 { get; set; }
        public decimal Quot150 { get; set; }
        public decimal Quot160 { get; set; }
        public decimal Quot170 { get; set; }
        public decimal Quot180 { get; set; }
        public decimal Quot190 { get; set; }
        public decimal Quot200 { get; set; }
        public decimal Quot210 { get; set; }
        public decimal Quot212 { get; set; }
        public decimal Quot214 { get; set; }
        public decimal Quot230 { get; set; }
        public decimal Quot240 { get; set; }
        public decimal Quot400 { get; set; }
        public decimal Quot410 { get; set; }
        public decimal Quot420 { get; set; }
        public decimal Quot500 { get; set; }
        public decimal Quot510 { get; set; }
        public decimal Quot520 { get; set; }
        public decimal Quot530 { get; set; }
        public decimal Quot535 { get; set; }
        public decimal Quot540 { get; set; }
        public byte Quot600 { get; set; }
        public decimal Quot610 { get; set; }
        public decimal Quot620 { get; set; }
        public decimal Quot630 { get; set; }
        public int Quot640 { get; set; }
        public int Quot650 { get; set; }
        public int Quot700 { get; set; }
        public string Quot710 { get; set; }
        public decimal Quot800 { get; set; }
        public decimal Quot801 { get; set; }
        public decimal Quot802 { get; set; }
        public decimal Quot803 { get; set; }
        public decimal Quot804 { get; set; }
        public decimal Quot805 { get; set; }
        public decimal Quot806 { get; set; }
        public byte Quot807 { get; set; }
        public decimal Quot808 { get; set; }
        public decimal Quot809 { get; set; }
        public decimal Quot810 { get; set; }
        public decimal Quot811 { get; set; }
        public decimal Quot812 { get; set; }
        public decimal Quot815 { get; set; }
        public decimal Quot816 { get; set; }
        public decimal Quot817 { get; set; }
        public decimal Quot818 { get; set; }
        public decimal Quot819 { get; set; }
        public decimal Quot820 { get; set; }
        public decimal Quot830 { get; set; }
        public decimal Quot840 { get; set; }
        public decimal Quot850 { get; set; }
        public System.DateTime Quot860 { get; set; }
        public byte[] Quotdtm { get; private set; }
        public string Quot048 { get; set; }
        public int Quot035 { get; set; }
        public System.DateTime Quot041 { get; set; }
        public string Quot051 { get; set; }
        public string Quot055 { get; set; }
        public decimal Quot720 { get; set; }
        public decimal Quot730 { get; set; }
        public decimal Quot740 { get; set; }
        public System.DateTime Quot831 { get; set; }
        public decimal Quot861 { get; set; }
        public string Quot862 { get; set; }
        public decimal Quot855 { get; set; }
        public decimal Quot865 { get; set; }
        public decimal Quot501 { get; set; }
        public decimal Quot780 { get; set; }
        public byte Quot790 { get; set; }
        public decimal Quot792 { get; set; }
        public decimal Quot795 { get; set; }
        public byte Quot796 { get; set; }
        public string Quot797 { get; set; }
        public byte Quot798 { get; set; }
        public string Quot799 { get; set; }
        public decimal Quot824 { get; set; }
        public string Quot825 { get; set; }
        public short Quot8271 { get; set; }
        public short Quot8272 { get; set; }
        public decimal Quot8281 { get; set; }
        public decimal Quot8282 { get; set; }
        public decimal Quot8291 { get; set; }
        public decimal Quot8292 { get; set; }
        public int Quot900 { get; set; }
        public decimal Quot785 { get; set; }
        public System.DateTime Quot870 { get; set; }
        public string Quot872 { get; set; }
        public decimal Quot550 { get; set; }
        public decimal Quot552 { get; set; }
        public decimal Quot554 { get; set; }
        public decimal Quot556 { get; set; }
        public decimal Quot558 { get; set; }
        public decimal Quot560 { get; set; }
        public decimal Quot149 { get; set; }
        public System.DateTime Quot580 { get; set; }
        public decimal Quot582 { get; set; }
        public decimal Quot584 { get; set; }
        public decimal Quot586 { get; set; }
        public string Quot588 { get; set; }
        public decimal Quot590 { get; set; }
        public decimal Quot592 { get; set; }
        public string Quot594 { get; set; }
        public decimal Quot596 { get; set; }
        public decimal Quot597 { get; set; }
        public System.DateTime Quot598 { get; set; }
        public int Quot910 { get; set; }
        public string Quot920 { get; set; }
        public decimal Quot760 { get; set; }
        public decimal Quot761 { get; set; }
        public decimal Quot762 { get; set; }
        public decimal Quot763 { get; set; }
        public decimal Quot764 { get; set; }
        public decimal Quot765 { get; set; }
        public decimal Quot766 { get; set; }
        public decimal Quot767 { get; set; }
        public decimal Quot768 { get; set; }
        public byte Quot769 { get; set; }
        public string Quot770 { get; set; }
        public string Quot771 { get; set; }
        public string Quot772 { get; set; }
        public string Quot773 { get; set; }
        public string Quot774 { get; set; }
        public decimal Quot856 { get; set; }
    }

}
