

namespace Generator
{

    public class Slad
    {
        public int Slad001 { get; set; }
        public System.DateTime Slad010 { get; set; }
        public string Slad020 { get; set; }
        public int Slad030 { get; set; }
        public string Slad040 { get; set; }
        public decimal Slad220 { get; set; }
        public decimal Slad230 { get; set; }
        public string Slad260 { get; set; }
        public decimal Slad270 { get; set; }
        public string Slad280 { get; set; }
        public string Slad290 { get; set; }
        public decimal Slad292 { get; set; }
        public decimal Slad294 { get; set; }
        public string Slad3101 { get; set; }
        public string Slad3102 { get; set; }
        public string Slad3103 { get; set; }
        public string Slad320 { get; set; }
        public string Slad3301 { get; set; }
        public string Slad3302 { get; set; }
        public string Slad3303 { get; set; }
        public short Slad3401 { get; set; }
        public short Slad3402 { get; set; }
        public short Slad3403 { get; set; }
        public decimal Slad3501 { get; set; }
        public decimal Slad3502 { get; set; }
        public decimal Slad3503 { get; set; }
        public string Slad3601 { get; set; }
        public string Slad3602 { get; set; }
        public string Slad3603 { get; set; }
        public System.DateTime Slad3621 { get; set; }
        public System.DateTime Slad3622 { get; set; }
        public System.DateTime Slad3623 { get; set; }
        public System.DateTime Slad3641 { get; set; }
        public System.DateTime Slad3642 { get; set; }
        public System.DateTime Slad3643 { get; set; }
        public decimal Slad3681 { get; set; }
        public decimal Slad3682 { get; set; }
        public decimal Slad3683 { get; set; }
        public decimal Slad3701 { get; set; }
        public decimal Slad3702 { get; set; }
        public decimal Slad3703 { get; set; }
        public decimal Slad3721 { get; set; }
        public decimal Slad3722 { get; set; }
        public decimal Slad3723 { get; set; }
        public string Slad410 { get; set; }
        public decimal Slad420 { get; set; }
        public string Slad430 { get; set; }
        public decimal Slad440 { get; set; }
        public decimal Slad445 { get; set; }
        public decimal Slad446 { get; set; }
        public decimal Slad447 { get; set; }
        public short Slad450 { get; set; }
        public byte Slad460 { get; set; }
        public short Slad470 { get; set; }
        public decimal Slad480 { get; set; }
        public decimal Slad485 { get; set; }
        public decimal Slad490 { get; set; }
        public decimal Slad496 { get; set; }
        public byte Slad497 { get; set; }
        public string Slad510 { get; set; }
        public string Slad520 { get; set; }
        public string Slad525 { get; set; }
        public byte Slad527 { get; set; }
        public string Slad530 { get; set; }
        public decimal Slad540 { get; set; }
        public string Slad550 { get; set; }
        public decimal Slad560 { get; set; }
        public short Slad570 { get; set; }
        public decimal Slad580 { get; set; }
        public decimal Slad590 { get; set; }
        public string Slad7101 { get; set; }
        public string Slad7102 { get; set; }
        public string Slad7103 { get; set; }
        public System.DateTime Slad7151 { get; set; }
        public System.DateTime Slad7152 { get; set; }
        public System.DateTime Slad7153 { get; set; }
        public string Slad720 { get; set; }
        public string Slad7281 { get; set; }
        public string Slad7282 { get; set; }
        public string Slad7283 { get; set; }
        public string Slad7291 { get; set; }
        public string Slad7292 { get; set; }
        public string Slad7293 { get; set; }
        public decimal Slad7301 { get; set; }
        public decimal Slad7302 { get; set; }
        public decimal Slad7303 { get; set; }
        public decimal Slad7321 { get; set; }
        public decimal Slad7322 { get; set; }
        public decimal Slad7323 { get; set; }
        public decimal Slad7331 { get; set; }
        public decimal Slad7332 { get; set; }
        public decimal Slad7333 { get; set; }
        public decimal Slad7341 { get; set; }
        public decimal Slad7342 { get; set; }
        public decimal Slad7343 { get; set; }
        public string Slad7371 { get; set; }
        public string Slad7372 { get; set; }
        public string Slad7373 { get; set; }
        public string Slad740 { get; set; }
        public short Slad800 { get; set; }
        public string Slad830 { get; set; }
        public string Slad900 { get; set; }
        public decimal Slad905 { get; set; }
        public decimal Slad910 { get; set; }
        public decimal Slad915 { get; set; }
        public decimal Slad920 { get; set; }
        public decimal Slad925 { get; set; }
        public decimal Slad930 { get; set; }
        public string Slad940 { get; set; }
        public decimal Slad945 { get; set; }
        public System.DateTime Slad946 { get; set; }
        public string Slad950 { get; set; }
        public string Slad955 { get; set; }
        public System.DateTime Slad960 { get; set; }
        public decimal Slad965 { get; set; }
        public string Slad970 { get; set; }
        public int Slad975 { get; set; }
        public decimal Slad980 { get; set; }
        public decimal Slad985 { get; set; }
        public string Slad810 { get; set; }
        public string Slad820 { get; set; }
        public string Slad935 { get; set; }
        public byte Slad325 { get; set; }
        public byte Slad725 { get; set; }
        public byte[] Sladdtm { get; private set; }
        public decimal Slad901 { get; set; }
        public string Slad902 { get; set; }
        public decimal Slad100 { get; set; }
        public decimal Slad110 { get; set; }
        public decimal Slad120 { get; set; }
        public decimal Slad130 { get; set; }
        public decimal Slad150 { get; set; }
        public System.DateTime Slad160 { get; set; }
        public System.DateTime Slad650 { get; set; }
        public int Slad660 { get; set; }
        public decimal Slad101 { get; set; }
        public decimal Slad105 { get; set; }
        public decimal Slad111 { get; set; }
        public decimal Slad121 { get; set; }
        public decimal Slad131 { get; set; }
        public decimal Slad151 { get; set; }
        public decimal Slad152 { get; set; }
        public decimal Slad155 { get; set; }
        public string Slad563 { get; set; }
        public string Slad566 { get; set; }
        public decimal Slad568 { get; set; }
        public int Slad321 { get; set; }
        public string Slad990 { get; set; }
        public System.DateTime Slad640 { get; set; }
        public System.DateTime Slad645 { get; set; }
        public string Slad374 { get; set; }
        public byte Slad380 { get; set; }
        public System.DateTime Slad991 { get; set; }
        public System.DateTime Slad992 { get; set; }
        public System.DateTime Slad993 { get; set; }
        public System.DateTime Slad994 { get; set; }
        public string Slad551 { get; set; }
        public string Slad552 { get; set; }
        public string Slad553 { get; set; }
        public decimal Slad107 { get; set; }
        public decimal Slad108 { get; set; }
        public string Slad571 { get; set; }
        public decimal Slad850 { get; set; }
        public decimal Slad860 { get; set; }
        public decimal Slad156 { get; set; }
        public decimal Slad143 { get; set; }
        public decimal Slad104 { get; set; }
        public System.DateTime Slad890 { get; set; }
        public string Slad600 { get; set; }
        public byte Slad6101 { get; set; }
        public byte Slad6102 { get; set; }
        public byte Slad6103 { get; set; }
        public byte Slad6104 { get; set; }
        public byte Slad6105 { get; set; }
        public byte Slad6106 { get; set; }
        public byte Slad6107 { get; set; }
        public byte Slad6108 { get; set; }
        public byte Slad6109 { get; set; }
        public byte Slad61010 { get; set; }
        public byte Slad61011 { get; set; }
        public byte Slad61012 { get; set; }
        public string Slad615 { get; set; }
        public byte Slad620 { get; set; }
        public System.DateTime Slad625 { get; set; }
        public string Slad630 { get; set; }
        public System.DateTime Slad635 { get; set; }
        public decimal Slad1581 { get; set; }
        public decimal Slad1582 { get; set; }
        public decimal Slad1583 { get; set; }
        public decimal Slad1584 { get; set; }
        public decimal Slad1585 { get; set; }
        public decimal Slad1586 { get; set; }
        public decimal Slad1587 { get; set; }
        public decimal Slad1588 { get; set; }
        public short Slad569 { get; set; }
        public decimal Slad591 { get; set; }
        public decimal Slad592 { get; set; }
        public decimal Slad595 { get; set; }
        public string Slad554 { get; set; }
        public byte Slad593 { get; set; }
        public int Slad486 { get; set; }
        public int Slad487 { get; set; }
        public int Slad488 { get; set; }
        public System.DateTime Slad489 { get; set; }
    }

}
